name = "polynomial-sepolia"
version = "1"
description = "Andromeda dev deployment"
preset = "main"
include = [
    "tomls/core.toml",
    "tomls/settings.toml",
    "tomls/permissions.toml",
    "tomls/permit-deniers.toml",
    "tomls/pools/main-pool.toml",
    "tomls/markets/spot-factory.toml",
    "tomls/markets/perps-factory.toml",
    "tomls/polynomial-sepolia-andromeda/spot/usdc.toml",
    "tomls/permit-all-perps-perpsSystem.toml",
    "tomls/polynomial-sepolia-andromeda/perps/referrers.toml",
    "tomls/polynomial-sepolia-andromeda/perps/global.toml",
    "tomls/polynomial-sepolia-andromeda/spot/global.toml",
    "tomls/polynomial-sepolia-andromeda/perps/fee-tier.toml",
    "tomls/oracles/perps-keeper-cost.toml",
    "tomls/polynomial-sepolia-andromeda/spot/eth.toml",
    "tomls/polynomial-sepolia-andromeda/collaterals/susdc.toml",
    "tomls/collaterals/susdc.toml",
    "tomls/polynomial-sepolia-andromeda/collaterals/sdai.toml",
    "tomls/oracles/pyth-sdai.toml",
    "tomls/oracles/pyth-usdc.toml",
    "tomls/oracles/sdai.toml",
    "tomls/collaterals/sdai.toml",
    "tomls/polynomial-sepolia-andromeda/collaterals/susde.toml",
    "tomls/oracles/pyth-susde.toml",
    "tomls/oracles/susde.toml",
    "tomls/collaterals/susde.toml",
    "tomls/polynomial-sepolia-andromeda/collaterals/usd0++.toml",
    "tomls/oracles/pyth-usd0++.toml",
    "tomls/oracles/usd0++.toml",
    "tomls/collaterals/usd0++.toml",
    "tomls/polynomial-sepolia-andromeda/perps/collaterals/usd.toml",
    "tomls/polynomial-sepolia-andromeda/perps/collaterals/eth.toml",
    "tomls/polynomial-sepolia-andromeda/rewards/fxeth_perps_liquidations_rewards.toml",
    "tomls/polynomial-sepolia-andromeda/perps/btc-invokes.toml",
    "tomls/oracles/pyth-btc.toml",
    "tomls/polynomial-sepolia-andromeda/perps/btc.toml",
    "tomls/polynomial-sepolia-andromeda/perps/eth-invokes.toml",
    "tomls/oracles/pyth-eth.toml",
    "tomls/polynomial-sepolia-andromeda/perps/eth.toml",
    "tomls/polynomial-sepolia-andromeda/perps/sol-invokes.toml",
    "tomls/oracles/pyth-sol.toml",
    "tomls/polynomial-sepolia-andromeda/perps/sol.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pepe-invokes.toml",
    "tomls/oracles/pyth-pepe.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pepe.toml",
    "tomls/polynomial-sepolia-andromeda/perps/wif-invokes.toml",
    "tomls/oracles/pyth-wif.toml",
    "tomls/polynomial-sepolia-andromeda/perps/wif.toml",
    "tomls/polynomial-sepolia-andromeda/perps/sui-invokes.toml",
    "tomls/oracles/pyth-sui.toml",
    "tomls/polynomial-sepolia-andromeda/perps/sui.toml",
    "tomls/polynomial-sepolia-andromeda/perps/aave-invokes.toml",
    "tomls/oracles/pyth-aave.toml",
    "tomls/polynomial-sepolia-andromeda/perps/aave.toml",
    "tomls/polynomial-sepolia-andromeda/perps/op-invokes.toml",
    "tomls/oracles/pyth-op.toml",
    "tomls/polynomial-sepolia-andromeda/perps/op.toml",
    "tomls/polynomial-sepolia-andromeda/perps/bonk-invokes.toml",
    "tomls/oracles/pyth-bonk.toml",
    "tomls/polynomial-sepolia-andromeda/perps/bonk.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pnut-invokes.toml",
    "tomls/oracles/pyth-pnut.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pnut.toml",
    "tomls/polynomial-sepolia-andromeda/perps/mog-invokes.toml",
    "tomls/oracles/pyth-mog.toml",
    "tomls/polynomial-sepolia-andromeda/perps/mog.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ena-invokes.toml",
    "tomls/oracles/pyth-ena.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ena.toml",
    "tomls/polynomial-sepolia-andromeda/perps/doge-invokes.toml",
    "tomls/oracles/pyth-doge.toml",
    "tomls/polynomial-sepolia-andromeda/perps/doge.toml",
    "tomls/polynomial-sepolia-andromeda/perps/eigen-invokes.toml",
    "tomls/oracles/pyth-eigen.toml",
    "tomls/polynomial-sepolia-andromeda/perps/eigen.toml",
    "tomls/polynomial-sepolia-andromeda/perps/xrp-invokes.toml",
    "tomls/oracles/pyth-xrp.toml",
    "tomls/polynomial-sepolia-andromeda/perps/xrp.toml",
    "tomls/polynomial-sepolia-andromeda/perps/tia-invokes.toml",
    "tomls/oracles/pyth-tia.toml",
    "tomls/polynomial-sepolia-andromeda/perps/tia.toml",
    "tomls/polynomial-sepolia-andromeda/perps/avax-invokes.toml",
    "tomls/oracles/pyth-avax.toml",
    "tomls/polynomial-sepolia-andromeda/perps/avax.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ltc-invokes.toml",
    "tomls/oracles/pyth-ltc.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ltc.toml",
    "tomls/polynomial-sepolia-andromeda/perps/link-invokes.toml",
    "tomls/oracles/pyth-link.toml",
    "tomls/polynomial-sepolia-andromeda/perps/link.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pengu-invokes.toml",
    "tomls/oracles/pyth-pengu.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pengu.toml",
    "tomls/pools/skibidi-pool.toml",
    "tomls/polynomial-sepolia-andromeda/perps/virtual-invokes.toml",
    "tomls/oracles/pyth-virtual.toml",
    "tomls/polynomial-sepolia-andromeda/perps/virtual.toml",
    "tomls/polynomial-sepolia-andromeda/perps/hype-invokes.toml",
    "tomls/oracles/pyth-hype.toml",
    "tomls/polynomial-sepolia-andromeda/perps/hype.toml",
    "tomls/polynomial-sepolia-andromeda/perps/fartcoin-invokes.toml",
    "tomls/oracles/pyth-fartcoin.toml",
    "tomls/polynomial-sepolia-andromeda/perps/fartcoin.toml",
    "tomls/polynomial-sepolia-andromeda/perps/move-invokes.toml",
    "tomls/oracles/pyth-move.toml",
    "tomls/polynomial-sepolia-andromeda/perps/move.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ai16z-invokes.toml",
    "tomls/oracles/pyth-ai16z.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ai16z.toml",
    "tomls/polynomial-sepolia-andromeda/perps/snx-invokes.toml",
    "tomls/oracles/pyth-snx.toml",
    "tomls/polynomial-sepolia-andromeda/perps/snx.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pyth-invokes.toml",
    "tomls/oracles/pyth-pyth.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pyth.toml",
    "tomls/polynomial-sepolia-andromeda/perps/spx-invokes.toml",
    "tomls/oracles/pyth-spx.toml",
    "tomls/polynomial-sepolia-andromeda/perps/spx.toml",
    "tomls/polynomial-sepolia-andromeda/perps/trump-invokes.toml",
    "tomls/oracles/pyth-trump.toml",
    "tomls/polynomial-sepolia-andromeda/perps/trump.toml",
]

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"

[setting.snx_package]
defaultValue = "polynomial-core:3.8.2"

[setting.perps_keeper_cost_package]
defaultValue = "fx-op-gas-price-oracle:3.8.2"

[setting.spot_market_package]
defaultValue = "fx-spot-market:3.8.3"

[setting.perps_market_package]
defaultValue = "fx-perps-market:3.9.2"

[setting.salt]
defaultValue = "andromeda-dev"

[setting.target_preset]
defaultValue = "main"

[setting.pyth_price_verification_address]
defaultValue = "0x23f0e8FAeE7bbb405E7A7C3d60138FCfd43d7509"

[setting.owner]
defaultValue = "0x2b02AAd6f1694E7D9c934B7b3Ec444541286cF0f"

[setting.deployer]
defaultValue = "0x2b02AAd6f1694E7D9c934B7b3Ec444541286cF0f"

[setting.minimum_liquidity_ratio]
defaultValue = "<%= parseEther('1.25') %>"

[setting.account_timeout_withdraw]
defaultValue = "86400"

[setting.main_pool_id]
defaultValue = "1"

[setting.skibidi_pool_id]
defaultValue = "69"

[setting.pool_owner]
defaultValue = "0x2b02AAd6f1694E7D9c934B7b3Ec444541286cF0f"

[provision.pyth_erc7412_wrapper]
source = "pyth-erc7412-wrapper:3.3.17"
targetPreset = "<%= settings.target_preset %>"

[provision.pyth_erc7412_wrapper.options]
salt = "<%= settings.salt %>"
pythAddress = "<%= settings.pyth_price_verification_address %>"

[invoke.setMainPoolConfig]
target = ["system.CoreProxy"]
func = "setPoolConfiguration"
args = [
    "<%= settings.main_pool_id %>",
    [
        { marketId = "<%= imports.perpsFactory.extras.superMarketId %>", weightD18 = 1, maxDebtShareValueD18 = "<%= parseEther('1') %>" },
    ],
]

[invoke.setMainPoolConfig.fromCall]
func = "getPoolOwner"
args = ["<%= settings.main_pool_id %>"]
