name = "polynomial-sepolia"
version = "1"
description = "Andromeda dev deployment"
preset = "main"
include = [
    "tomls/core.toml",
    "tomls/settings.toml",
    "tomls/permissions.toml",
    "tomls/permit-deniers.toml",
    "tomls/pools/main-pool.toml",
    "tomls/markets/spot-factory.toml",
    "tomls/markets/perps-factory.toml",
    "tomls/polynomial-sepolia-andromeda/spot/usdc.toml",
    "tomls/permit-all-perps-perpsSystem.toml",
    "tomls/polynomial-sepolia-andromeda/perps/referrers.toml",
    "tomls/polynomial-sepolia-andromeda/perps/global.toml",
    "tomls/polynomial-sepolia-andromeda/spot/global.toml",
    "tomls/polynomial-sepolia-andromeda/perps/fee-tier.toml",
    "tomls/oracles/perps-keeper-cost.toml",
    "tomls/polynomial-sepolia-andromeda/spot/eth.toml",
    "tomls/polynomial-sepolia-andromeda/spot/op.toml",
    "tomls/polynomial-sepolia-andromeda/spot/wstEth.toml",
    "tomls/polynomial-sepolia-andromeda/spot/solvBtc.toml",
    "tomls/polynomial-sepolia-andromeda/spot/weEth.toml",
    "tomls/polynomial-sepolia-andromeda/spot/cbBtc.toml",
    "tomls/polynomial-sepolia-andromeda/spot/usdt.toml",
    "tomls/polynomial-sepolia-andromeda/spot/usds.toml",
    "tomls/polynomial-sepolia-andromeda/spot/rseth.toml",
    "tomls/polynomial-sepolia-andromeda/collaterals/susdc.toml",
    "tomls/collaterals/susdc.toml",
    "tomls/polynomial-sepolia-andromeda/collaterals/sdai.toml",
    "tomls/oracles/pyth-sdai.toml",
    "tomls/oracles/pyth-usdc.toml",
    "tomls/oracles/sdai.toml",
    "tomls/collaterals/sdai.toml",
    "tomls/polynomial-sepolia-andromeda/collaterals/susde.toml",
    "tomls/oracles/pyth-susde.toml",
    "tomls/oracles/susde.toml",
    "tomls/collaterals/susde.toml",
    "tomls/polynomial-sepolia-andromeda/collaterals/usd0++.toml",
    "tomls/oracles/pyth-usd0++.toml",
    "tomls/oracles/usd0++.toml",
    "tomls/collaterals/usd0++.toml",
    "tomls/polynomial-sepolia-andromeda/perps/collaterals/usd.toml",
    "tomls/polynomial-sepolia-andromeda/perps/collaterals/eth.toml",
    "tomls/polynomial-sepolia-andromeda/perps/collaterals/op.toml",
    "tomls/polynomial-sepolia-andromeda/perps/collaterals/wstEth.toml",
    "tomls/polynomial-sepolia-andromeda/perps/collaterals/solvBtc.toml",
    "tomls/polynomial-sepolia-andromeda/perps/collaterals/weEth.toml",
    "tomls/polynomial-sepolia-andromeda/perps/collaterals/cbBtc.toml",
    "tomls/polynomial-sepolia-andromeda/perps/collaterals/usdt.toml",
    "tomls/polynomial-sepolia-andromeda/perps/collaterals/usds.toml",
    "tomls/polynomial-sepolia-andromeda/perps/collaterals/rseth.toml",
    "tomls/polynomial-sepolia-andromeda/rewards/fxeth_perps_liquidations_rewards.toml",
    "tomls/polynomial-sepolia-andromeda/rewards/fxop_perps_liquidations_rewards.toml",
    "tomls/polynomial-sepolia-andromeda/rewards/fxwsteth_perps_liquidations_rewards.toml",
    "tomls/polynomial-sepolia-andromeda/rewards/fxsolvbtc_perps_liquidations_rewards.toml",
    "tomls/polynomial-sepolia-andromeda/rewards/fxweeth_perps_liquidations_rewards.toml",
    "tomls/polynomial-sepolia-andromeda/rewards/fxcbbtc_perps_liquidations_rewards.toml",
    "tomls/polynomial-sepolia-andromeda/rewards/fxusdt_perps_liquidations_rewards.toml",
    "tomls/polynomial-sepolia-andromeda/rewards/fxusds_perps_liquidations_rewards.toml",
    "tomls/polynomial-sepolia-andromeda/rewards/fxrseth_perps_liquidations_rewards.toml",
    "tomls/polynomial-sepolia-andromeda/perps/btc-invokes.toml",
    "tomls/oracles/pyth-wsteth.toml",
    "tomls/oracles/pyth-solvbtc.toml",
    "tomls/oracles/pyth-weeth.toml",
    "tomls/oracles/pyth-cbbtc.toml",
    "tomls/oracles/pyth-usdt.toml",
    "tomls/oracles/pyth-usds.toml",
    "tomls/oracles/pyth-rseth.toml",
    "tomls/oracles/pyth-btc.toml",
    "tomls/polynomial-sepolia-andromeda/perps/btc.toml",
    "tomls/polynomial-sepolia-andromeda/perps/eth-invokes.toml",
    "tomls/oracles/pyth-eth.toml",
    "tomls/polynomial-sepolia-andromeda/perps/eth.toml",
    "tomls/polynomial-sepolia-andromeda/perps/sol-invokes.toml",
    "tomls/oracles/pyth-sol.toml",
    "tomls/polynomial-sepolia-andromeda/perps/sol.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pepe-invokes.toml",
    "tomls/oracles/pyth-pepe.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pepe.toml",
    "tomls/polynomial-sepolia-andromeda/perps/wif-invokes.toml",
    "tomls/oracles/pyth-wif.toml",
    "tomls/polynomial-sepolia-andromeda/perps/wif.toml",
    "tomls/polynomial-sepolia-andromeda/perps/sui-invokes.toml",
    "tomls/oracles/pyth-sui.toml",
    "tomls/polynomial-sepolia-andromeda/perps/sui.toml",
    "tomls/polynomial-sepolia-andromeda/perps/aave-invokes.toml",
    "tomls/oracles/pyth-aave.toml",
    "tomls/polynomial-sepolia-andromeda/perps/aave.toml",
    "tomls/polynomial-sepolia-andromeda/perps/op-invokes.toml",
    "tomls/oracles/pyth-op.toml",
    "tomls/polynomial-sepolia-andromeda/perps/op.toml",
    "tomls/polynomial-sepolia-andromeda/perps/bonk-invokes.toml",
    "tomls/oracles/pyth-bonk.toml",
    "tomls/polynomial-sepolia-andromeda/perps/bonk.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pnut-invokes.toml",
    "tomls/oracles/pyth-pnut.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pnut.toml",
    "tomls/polynomial-sepolia-andromeda/perps/mog-invokes.toml",
    "tomls/oracles/pyth-mog.toml",
    "tomls/polynomial-sepolia-andromeda/perps/mog.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ena-invokes.toml",
    "tomls/oracles/pyth-ena.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ena.toml",
    "tomls/polynomial-sepolia-andromeda/perps/doge-invokes.toml",
    "tomls/oracles/pyth-doge.toml",
    "tomls/polynomial-sepolia-andromeda/perps/doge.toml",
    "tomls/polynomial-sepolia-andromeda/perps/eigen-invokes.toml",
    "tomls/oracles/pyth-eigen.toml",
    "tomls/polynomial-sepolia-andromeda/perps/eigen.toml",
    "tomls/polynomial-sepolia-andromeda/perps/xrp-invokes.toml",
    "tomls/oracles/pyth-xrp.toml",
    "tomls/polynomial-sepolia-andromeda/perps/xrp.toml",
    "tomls/polynomial-sepolia-andromeda/perps/tia-invokes.toml",
    "tomls/oracles/pyth-tia.toml",
    "tomls/polynomial-sepolia-andromeda/perps/tia.toml",
    "tomls/polynomial-sepolia-andromeda/perps/avax-invokes.toml",
    "tomls/oracles/pyth-avax.toml",
    "tomls/polynomial-sepolia-andromeda/perps/avax.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ltc-invokes.toml",
    "tomls/oracles/pyth-ltc.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ltc.toml",
    "tomls/polynomial-sepolia-andromeda/perps/link-invokes.toml",
    "tomls/oracles/pyth-link.toml",
    "tomls/polynomial-sepolia-andromeda/perps/link.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pengu-invokes.toml",
    "tomls/oracles/pyth-pengu.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pengu.toml",
    "tomls/pools/skibidi-pool.toml",
    "tomls/polynomial-sepolia-andromeda/perps/virtual-invokes.toml",
    "tomls/oracles/pyth-virtual.toml",
    "tomls/polynomial-sepolia-andromeda/perps/virtual.toml",
    "tomls/polynomial-sepolia-andromeda/perps/hype-invokes.toml",
    "tomls/oracles/pyth-hype.toml",
    "tomls/polynomial-sepolia-andromeda/perps/hype.toml",
    "tomls/polynomial-sepolia-andromeda/perps/fartcoin-invokes.toml",
    "tomls/oracles/pyth-fartcoin.toml",
    "tomls/polynomial-sepolia-andromeda/perps/fartcoin.toml",
    "tomls/polynomial-sepolia-andromeda/perps/move-invokes.toml",
    "tomls/oracles/pyth-move.toml",
    "tomls/polynomial-sepolia-andromeda/perps/move.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ai16z-invokes.toml",
    "tomls/oracles/pyth-ai16z.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ai16z.toml",
    "tomls/polynomial-sepolia-andromeda/perps/snx-invokes.toml",
    "tomls/oracles/pyth-snx.toml",
    "tomls/polynomial-sepolia-andromeda/perps/snx.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pyth-invokes.toml",
    "tomls/oracles/pyth-pyth.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pyth.toml",
    "tomls/polynomial-sepolia-andromeda/perps/spx-invokes.toml",
    "tomls/oracles/pyth-spx.toml",
    "tomls/polynomial-sepolia-andromeda/perps/spx.toml",
    "tomls/polynomial-sepolia-andromeda/perps/trump-invokes.toml",
    "tomls/oracles/pyth-trump.toml",
    "tomls/polynomial-sepolia-andromeda/perps/trump.toml",
    "tomls/polynomial-sepolia-andromeda/perps/s-invokes.toml",
    "tomls/oracles/pyth-s.toml",
    "tomls/polynomial-sepolia-andromeda/perps/s.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ondo-invokes.toml",
    "tomls/oracles/pyth-ondo.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ondo.toml",
    "tomls/polynomial-sepolia-andromeda/perps/jup-invokes.toml",
    "tomls/oracles/pyth-jup.toml",
    "tomls/polynomial-sepolia-andromeda/perps/jup.toml",
    "tomls/polynomial-sepolia-andromeda/perps/bera-invokes.toml",
    "tomls/oracles/pyth-bera.toml",
    "tomls/polynomial-sepolia-andromeda/perps/bera.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ada-invokes.toml",
    "tomls/oracles/pyth-ada.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ada.toml",
    "tomls/polynomial-sepolia-andromeda/perps/bnb-invokes.toml",
    "tomls/oracles/pyth-bnb.toml",
    "tomls/polynomial-sepolia-andromeda/perps/bnb.toml",
    "tomls/polynomial-sepolia-andromeda/perps/arb-invokes.toml",
    "tomls/oracles/pyth-arb.toml",
    "tomls/polynomial-sepolia-andromeda/perps/arb.toml",
    "tomls/polynomial-sepolia-andromeda/perps/kaito-invokes.toml",
    "tomls/oracles/pyth-kaito.toml",
    "tomls/polynomial-sepolia-andromeda/perps/kaito.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ip-invokes.toml",
    "tomls/oracles/pyth-ip.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ip.toml",
    "tomls/polynomial-sepolia-andromeda/perps/hbar-invokes.toml",
    "tomls/oracles/pyth-hbar.toml",
    "tomls/polynomial-sepolia-andromeda/perps/hbar.toml",
    "tomls/polynomial-sepolia-andromeda/perps/bch-invokes.toml",
    "tomls/oracles/pyth-bch.toml",
    "tomls/polynomial-sepolia-andromeda/perps/bch.toml",
    "tomls/polynomial-sepolia-andromeda/perps/zora-invokes.toml",
    "tomls/oracles/pyth-zora.toml",
    "tomls/polynomial-sepolia-andromeda/perps/zora.toml",
    "tomls/polynomial-sepolia-andromeda/perps/cookie-invokes.toml",
    "tomls/oracles/pyth-cookie.toml",
    "tomls/polynomial-sepolia-andromeda/perps/cookie.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ape-invokes.toml",
    "tomls/oracles/pyth-ape.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ape.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ldo-invokes.toml",
    "tomls/oracles/pyth-ldo.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ldo.toml",
    "tomls/polynomial-sepolia-andromeda/perps/solv-invokes.toml",
    "tomls/oracles/pyth-solv.toml",
    "tomls/polynomial-sepolia-andromeda/perps/solv.toml",
    "tomls/polynomial-sepolia-andromeda/perps/alt-invokes.toml",
    "tomls/oracles/pyth-alt.toml",
    "tomls/polynomial-sepolia-andromeda/perps/alt.toml",
    "tomls/polynomial-sepolia-andromeda/perps/atom-invokes.toml",
    "tomls/oracles/pyth-atom.toml",
    "tomls/polynomial-sepolia-andromeda/perps/atom.toml",
    "tomls/polynomial-sepolia-andromeda/perps/floki-invokes.toml",
    "tomls/oracles/pyth-floki.toml",
    "tomls/polynomial-sepolia-andromeda/perps/floki.toml",
    "tomls/polynomial-sepolia-andromeda/perps/wct-invokes.toml",
    "tomls/oracles/pyth-wct.toml",
    "tomls/polynomial-sepolia-andromeda/perps/wct.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pendle-invokes.toml",
    "tomls/oracles/pyth-pendle.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pendle.toml",
    "tomls/polynomial-sepolia-andromeda/perps/grt-invokes.toml",
    "tomls/oracles/pyth-grt.toml",
    "tomls/polynomial-sepolia-andromeda/perps/grt.toml",
    "tomls/polynomial-sepolia-andromeda/perps/aero-invokes.toml",
    "tomls/oracles/pyth-aero.toml",
    "tomls/polynomial-sepolia-andromeda/perps/aero.toml",
    "tomls/polynomial-sepolia-andromeda/perps/morpho-invokes.toml",
    "tomls/oracles/pyth-morpho.toml",
    "tomls/polynomial-sepolia-andromeda/perps/morpho.toml",
    "tomls/polynomial-sepolia-andromeda/perps/wld-invokes.toml",
    "tomls/oracles/pyth-wld.toml",
    "tomls/polynomial-sepolia-andromeda/perps/wld.toml",
    "tomls/polynomial-sepolia-andromeda/perps/aixbt-invokes.toml",
    "tomls/oracles/pyth-aixbt.toml",
    "tomls/polynomial-sepolia-andromeda/perps/aixbt.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ethfi-invokes.toml",
    "tomls/oracles/pyth-ethfi.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ethfi.toml",
    "tomls/polynomial-sepolia-andromeda/perps/merl-invokes.toml",
    "tomls/oracles/pyth-merl.toml",
    "tomls/polynomial-sepolia-andromeda/perps/merl.toml",
    "tomls/polynomial-sepolia-andromeda/perps/stx-invokes.toml",
    "tomls/oracles/pyth-stx.toml",
    "tomls/polynomial-sepolia-andromeda/perps/stx.toml",
    "tomls/polynomial-sepolia-andromeda/perps/prcl-invokes.toml",
    "tomls/oracles/pyth-prcl.toml",
    "tomls/polynomial-sepolia-andromeda/perps/prcl.toml",
    "tomls/polynomial-sepolia-andromeda/perps/apt-invokes.toml",
    "tomls/oracles/pyth-apt.toml",
    "tomls/polynomial-sepolia-andromeda/perps/apt.toml",
    "tomls/polynomial-sepolia-andromeda/perps/nxpc-invokes.toml",
    "tomls/oracles/pyth-nxpc.toml",
    "tomls/polynomial-sepolia-andromeda/perps/nxpc.toml",
    "tomls/polynomial-sepolia-andromeda/perps/huma-invokes.toml",
    "tomls/oracles/pyth-huma.toml",
    "tomls/polynomial-sepolia-andromeda/perps/huma.toml",
    "tomls/polynomial-sepolia-andromeda/perps/zeta-invokes.toml",
    "tomls/oracles/pyth-zeta.toml",
    "tomls/polynomial-sepolia-andromeda/perps/zeta.toml",
    "tomls/polynomial-sepolia-andromeda/perps/fil-invokes.toml",
    "tomls/oracles/pyth-fil.toml",
    "tomls/polynomial-sepolia-andromeda/perps/fil.toml",
    "tomls/polynomial-sepolia-andromeda/perps/b3-invokes.toml",
    "tomls/oracles/pyth-b3.toml",
    "tomls/polynomial-sepolia-andromeda/perps/b3.toml",
    "tomls/polynomial-sepolia-andromeda/perps/resolv-invokes.toml",
    "tomls/oracles/pyth-resolv.toml",
    "tomls/polynomial-sepolia-andromeda/perps/resolv.toml",
    "tomls/polynomial-sepolia-andromeda/perps/cake-invokes.toml",
    "tomls/oracles/pyth-cake.toml",
    "tomls/polynomial-sepolia-andromeda/perps/cake.toml",
    "tomls/polynomial-sepolia-andromeda/perps/zro-invokes.toml",
    "tomls/oracles/pyth-zro.toml",
    "tomls/polynomial-sepolia-andromeda/perps/zro.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ton-invokes.toml",
    "tomls/oracles/pyth-ton.toml",
    "tomls/polynomial-sepolia-andromeda/perps/ton.toml",
    "tomls/polynomial-sepolia-andromeda/perps/jto-invokes.toml",
    "tomls/oracles/pyth-jto.toml",
    "tomls/polynomial-sepolia-andromeda/perps/jto.toml",
    "tomls/polynomial-sepolia-andromeda/perps/arkm-invokes.toml",
    "tomls/oracles/pyth-arkm.toml",
    "tomls/polynomial-sepolia-andromeda/perps/arkm.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pump-invokes.toml",
    "tomls/oracles/pyth-pump.toml",
    "tomls/polynomial-sepolia-andromeda/perps/pump.toml",
]

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"

[setting.snx_package]
defaultValue = "polynomial-core:3.9.7"

[setting.perps_keeper_cost_package]
defaultValue = "fx-op-gas-price-oracle:3.8.2"

[setting.spot_market_package]
defaultValue = "fx-spot-market:3.9.7"

[setting.perps_market_package]
defaultValue = "fx-perps-market:3.10.1"

[setting.salt]
defaultValue = "andromeda-dev"

[setting.target_preset]
defaultValue = "main"

[setting.pyth_price_verification_address]
defaultValue = "0x23f0e8FAeE7bbb405E7A7C3d60138FCfd43d7509"

[setting.pyth_lazer_price_verification_address]
defaultValue = "0xACeA761c27A909d4D3895128EBe6370FDE2dF481"

[setting.owner]
defaultValue = "0x2b02AAd6f1694E7D9c934B7b3Ec444541286cF0f"

[setting.deployer]
defaultValue = "0x2b02AAd6f1694E7D9c934B7b3Ec444541286cF0f"

[setting.minimum_liquidity_ratio]
defaultValue = "<%= parseEther('1.25') %>"

[setting.account_timeout_withdraw]
defaultValue = "86400"

[setting.main_pool_id]
defaultValue = "1"

[setting.skibidi_pool_id]
defaultValue = "69"

[setting.pool_owner]
defaultValue = "0x2b02AAd6f1694E7D9c934B7b3Ec444541286cF0f"

[provision.pyth_erc7412_wrapper]
source = "fx-pyth-erc7412-wrapper:3.4.0"
targetPreset = "<%= settings.target_preset %>"

[provision.pyth_erc7412_wrapper.options]
salt = "<%= settings.salt %>"
pythAddress = "<%= settings.pyth_price_verification_address %>"

[provision.pyth_lazer_erc7412_wrapper]
source = "fx-pyth-lazer-erc7412-wrapper:0.0.2"
targetPreset = "<%= settings.target_preset %>"

[provision.pyth_lazer_erc7412_wrapper.options]
salt = "<%= settings.salt %>"
pythAddress = "<%= settings.pyth_lazer_price_verification_address %>"

[invoke.setMainPoolConfig]
target = [
    "system.CoreProxy",
]
func = "setPoolConfiguration"
args = [
    "<%= settings.main_pool_id %>",
    [
        { marketId = "<%= imports.perpsFactory.extras.superMarketId %>", weightD18 = 1, maxDebtShareValueD18 = "<%= parseEther('1') %>" },
    ],
]

[invoke.setMainPoolConfig.fromCall]
func = "getPoolOwner"
args = [
    "<%= settings.main_pool_id %>",
]
