include = ["./settlement-settings.toml"]

[setting.bigCapSettlementDelay]
defaultValue = "2"

[setting.bigCapSettlementWindowDuration]
defaultValue = "30"

[setting.bigCapDefaultStalenessTolerance]
defaultValue = "3600"

[setting.bigCapStrictStalenessTolerance]
defaultValue = "60"
