[setting.perpsArbFeedId]
defaultValue = "0x3fa4252848f9f0a1480be62745a4629d9eb1322aebab8a791e344b3b9c1adcf5"

[setting.perpsArbMarketId]
defaultValue = "3700"

[setting.perpsArbSkewScale]
defaultValue = "<%= String(50_000_000) %>"

[setting.perpsArbMaxFundingVelocity]
defaultValue = "24"

[setting.perpsArbMakerFeeRatio]
defaultValue = "0.0005"

[setting.perpsArbTakerFeeRatio]
defaultValue = "0.0008"

[setting.perpsArbLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsArbLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsArbMaxMarketSize]
defaultValue = "<%= String(247220.12) %>"

[setting.perpsArbMaxMarketValue]
defaultValue = "<%= String(96_825) %>"

[setting.perpsArbInitialMarginRatio]
defaultValue = "1.2783223816388807"

[setting.perpsArbMaintenanceMarginScalar]
defaultValue = "0.317"

[setting.perpsArbMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsArbFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsArbMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsArbMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsArbMinimumPositionMargin]
defaultValue = "50"

[setting.perpsArbLockedOiRatio]
defaultValue = "0.5"

[setting.perpsArbSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsArbMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsArbEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
