[setting.perpsAtomFeedId]
defaultValue = "0xb00b60f88b03a6a625a8d1c048c3f66653edf217439983d037e7222c4e612819"

[setting.perpsAtomMarketId]
defaultValue = "4800"

[setting.perpsAtomSkewScale]
defaultValue = "<%= String(840_310) %>"

[setting.perpsAtomMaxFundingVelocity]
defaultValue = "24"

[setting.perpsAtomMakerFeeRatio]
defaultValue = "0.0005"

[setting.perpsAtomTakerFeeRatio]
defaultValue = "0.0008"

[setting.perpsAtomLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsAtomLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsAtomMaxMarketSize]
defaultValue = "<%= String(16_361) %>"

[setting.perpsAtomMaxMarketValue]
defaultValue = "<%= String(71_661) %>"

[setting.perpsAtomInitialMarginRatio]
defaultValue = "0.10684586953437263"

[setting.perpsAtomMaintenanceMarginScalar]
defaultValue = "0.26"

[setting.perpsAtomMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsAtomFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsAtomMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsAtomMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsAtomMinimumPositionMargin]
defaultValue = "25"

[setting.perpsAtomLockedOiRatio]
defaultValue = "0.5"

[setting.perpsAtomSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsAtomMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsAtomEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
