[setting.pythBonkFeedId]
defaultValue = "0x72b021217ca3fe68922a19aaf990109cb9d84e9ad004b4d2025ad6f529314419"

[setting.bonkPerpsMarketId]
defaultValue = "900"

[setting.perpsBonkSkewScale]
defaultValue = "<%= String(1_000_000_000_000) %>"

[setting.perpsBonkMaxFundingVelocity]
defaultValue = "36"

[setting.perpsBonkLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsBonkLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsBonkMakerFeeRatio]
defaultValue = "0.0005"

[setting.perpsBonkTakerFeeRatio]
defaultValue = "0.0008"

[setting.perpsBonkMaxMarketSize]
defaultValue = "<%= String(7005964282.03) %>"

[setting.perpsBonkMaxMarketValue]
defaultValue = "<%= String(122_081) %>"

[setting.perpsBonkInitialMarginRatio]
defaultValue = "2.27"

[setting.perpsBonkMinimumInitialMarginRatio]
defaultValue = "0.04"

[setting.perpsBonkMaintenanceMarginScalar]
defaultValue = "0.38"

[setting.perpsBonkFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsBonkMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsBonkMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsBonkMinimumPositionMargin]
defaultValue = "50"

[setting.perpsBonkLockedOiRatio]
defaultValue = "0.5"

[setting.perpsBonkSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsBonkMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsBonkEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
