[setting.pythEthFeedId]
# https://pyth.network/developers/price-feed-ids
defaultValue = "0xff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace"

[setting.ethPerpsMarketId]
defaultValue = "100"

[setting.perpsEthSkewScale]
defaultValue = "2000000"

[setting.perpsEthMaxFundingVelocity]
defaultValue = "9"

[setting.perpsEthLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsEthLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsEthMakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsEthTakerFeeRatio]
defaultValue = "0.0005"

[setting.perpsEthMaxMarketSize]
defaultValue = "155"

[setting.perpsEthMaxMarketValue]
defaultValue = "500000"

[setting.perpsEthInitialMarginRatio]
defaultValue = "8.92"

[setting.perpsEthMinimumInitialMarginRatio]
defaultValue = "0.02"

[setting.perpsEthMaintenanceMarginScalar]
defaultValue = "0.28"

[setting.perpsEthFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsEthMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsEthMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsEthMinimumPositionMargin]
defaultValue = "50"

[setting.perpsEthLockedOiRatio]
defaultValue = "0.5"

[setting.perpsEthSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsEthMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsEthEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
