[invoke.setEndorsedFeeTierUpdater]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setEndorsedFeeTierUpdater"
args = ["0x7AF6F5F8bc0103fcaB892C3d1efbE38ed8cF775E"]

[invoke.setFeeTier1]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFeeTier"
args = ["1", "3750", "1250"]

[invoke.setFeeTier2]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFeeTier"
args = ["2", "4375", "1667"]

[invoke.setFeeTier3]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFeeTier"
args = ["3", "5000", "2500"]

[invoke.setFeeTier4]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFeeTier"
args = ["4", "5625", "3333"]

[invoke.setFeeTier5]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFeeTier"
args = ["5", "6250", "4167"]

[invoke.setFeeTier6]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFeeTier"
args = ["6", "6875", "5000"]

[invoke.setFeeTier7]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFeeTier"
args = ["7", "7500", "5833"]

[invoke.setFeeTier8]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFeeTier"
args = ["8", "8750", "6667"]

[invoke.setFeeTier9]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFeeTier"
args = ["9", "10000", "7500"]