[setting.perpsHbarFeedId]
defaultValue = "0x3728e591097635310e6341af53db8b7ee42da9b3a8d918f9463ce9cca886dfbd"

[setting.perpsHbarMarketId]
defaultValue = "4000"

[setting.perpsHbarSkewScale]
defaultValue = "<%= String(90_000_000) %>"

[setting.perpsHbarMaxFundingVelocity]
defaultValue = "24"

[setting.perpsHbarMakerFeeRatio]
defaultValue = "0.0004"

[setting.perpsHbarTakerFeeRatio]
defaultValue = "0.0006"

[setting.perpsHbarLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsHbarLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsHbarMaxMarketSize]
defaultValue = "<%= String(304_065) %>"

[setting.perpsHbarMaxMarketValue]
defaultValue = "<%= String(71_617) %>"

[setting.perpsHbarInitialMarginRatio]
defaultValue = "0.9552005471050908"

[setting.perpsHbarMaintenanceMarginScalar]
defaultValue = "0.26"

[setting.perpsHbarMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsHbarFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsHbarMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsHbarMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsHbarMinimumPositionMargin]
defaultValue = "25"

[setting.perpsHbarLockedOiRatio]
defaultValue = "0.5"

[setting.perpsHbarSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsHbarMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsHbarEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
