[setting.perpsJupFeedId]
defaultValue = "0x0a0408d619e9380abad35060f9192039ed5042fa6f82301d0e48bb52be830996"

[setting.perpsJupMarketId]
defaultValue = "3200"

[setting.perpsJupSkewScale]
defaultValue = "<%= String(2_500_000) %>"

[setting.perpsJupMaxFundingVelocity]
defaultValue = "24"

[setting.perpsJupMakerFeeRatio]
defaultValue = "0.0005"

[setting.perpsJupTakerFeeRatio]
defaultValue = "0.0008"

[setting.perpsJupLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsJupLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsJupMaxMarketSize]
defaultValue = "<%= String(204266.58) %>"

[setting.perpsJupMaxMarketValue]
defaultValue = "<%= String(96_825) %>"

[setting.perpsJupInitialMarginRatio]
defaultValue = "2.0641494610555444"

[setting.perpsJupMaintenanceMarginScalar]
defaultValue = "0.317"

[setting.perpsJupMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsJupFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsJupMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsJupMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsJupMinimumPositionMargin]
defaultValue = "50"

[setting.perpsJupLockedOiRatio]
defaultValue = "0.5"

[setting.perpsJupSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsJupMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsJupEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
