include = [
    "../../oracles/pyth-kaito.toml",
    "../../markets/common/bigcap-settings.toml",
]

[setting.perpsKaitoMarketId]

[setting.perpsKaitoSkewScale]

[setting.perpsKaitoMaxFundingVelocity]

[setting.perpsKaitoMakerFeeRatio]

[setting.perpsKaitoTakerFeeRatio]

[setting.perpsKaitoMaxMarketSize]

[setting.perpsKaitoInitialMarginRatio]

[setting.perpsKaitoMaintenanceMarginScalar]

[setting.perpsKaitoMinimumInitialMarginRatio]

[setting.perpsKaitoFlagRewardRatioD18]

[setting.perpsKaitoMaxLiquidationLimitAccumulationMultiplier]

[setting.perpsKaitoMaxSecondsInLiquidationWindow]

[setting.perpsKaitoMinimumPositionMargin]

[setting.perpsKaitoLockedOiRatio]

[setting.perpsKaitoSynthMaxCollateralAmount]

[setting.perpsKaitoMaxLiquidationPd]

[setting.perpsKaitoEndorsedLiquidator]

[invoke.createperpsKaitoMarket]
target = [
    "perpsFactory.PerpsMarketProxy",
]
func = "createMarket"
args = [
    "<%= settings.perpsKaitoMarketId %>",
    "Kaito",
    "KAITO",
]
depends = [
    "provision.system",
    "provision.perpsFactory",
]

[invoke.createperpsKaitoMarket.fromCall]
func = "owner"

[invoke.setperpsKaitoPrice]
target = [
    "perpsFactory.PerpsMarketProxy",
]
func = "updatePriceData"
args = [
    "<%= settings.perpsKaitoMarketId %>",
    "<%= extras.perpsKaito_oracle_id %>",
    "<%= settings.bigCapStrictStalenessTolerance %>",
]
depends = [
    "invoke.createperpsKaitoMarket",
]

[invoke.setperpsKaitoPrice.fromCall]
func = "owner"

[invoke.addperpsKaitoSettlementStrategy]
target = [
    "perpsFactory.PerpsMarketProxy",
]
func = "addSettlementStrategy"
args = [
    "<%= settings.perpsKaitoMarketId %>",
    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
depends = [
    "invoke.createperpsKaitoMarket",
]

[invoke.addperpsKaitoSettlementStrategy.fromCall]
func = "owner"

[invoke.addperpsKaitoSettlementStrategy.extra.perpsKaito_pyth_settlement_strategy]
event = "SettlementStrategyAdded"
arg = 2

[invoke.setperpsKaitoSettlementStrategy]
target = [
    "perpsFactory.PerpsMarketProxy",
]
func = "setSettlementStrategy"
args = [
    "<%= settings.perpsKaitoMarketId %>",
    "<%= extras.perpsKaito_pyth_settlement_strategy %>",
    { strategyType = "0", settlementDelay = "<%= settings.bigCapSettlementDelay %>", settlementWindowDuration = "<%= settings.bigCapSettlementWindowDuration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.perpsKaitoFeedId %>", settlementReward = "<%= parseEther(settings.settlementReward) %>", disabled = false, commitmentPriceDelay = "2" },
]
depends = [
    "provision.perpsFactory",
    "setting.perpsKaitoMarketId",
    "invoke.addperpsKaitoSettlementStrategy",
    "provision.pyth_erc7412_wrapper",
    "setting.bigCapSettlementDelay",
    "setting.bigCapSettlementWindowDuration",
    "setting.perpsKaitoFeedId",
    "setting.settlementReward",
]

[invoke.setperpsKaitoSettlementStrategy.fromCall]
func = "owner"

[invoke.setperpsKaitoFundingParameters]
target = [
    "perpsFactory.PerpsMarketProxy",
]
func = "setFundingParameters"
args = [
    "<%= settings.perpsKaitoMarketId %>",
    "<%= parseEther(settings.perpsKaitoSkewScale) %>",
    "<%= parseEther(settings.perpsKaitoMaxFundingVelocity) %>",
]
depends = [
    "invoke.createperpsKaitoMarket",
]

[invoke.setperpsKaitoFundingParameters.fromCall]
func = "owner"

[invoke.setperpsKaitoOrderFees]
target = [
    "perpsFactory.PerpsMarketProxy",
]
func = "setOrderFees"
args = [
    "<%= settings.perpsKaitoMarketId %>",
    "<%= parseEther(settings.perpsKaitoMakerFeeRatio) %>",
    "<%= parseEther(settings.perpsKaitoTakerFeeRatio) %>",
]
depends = [
    "invoke.createperpsKaitoMarket",
]

[invoke.setperpsKaitoOrderFees.fromCall]
func = "owner"

[invoke.setperpsKaitoMaxMarketSize]
target = [
    "perpsFactory.PerpsMarketProxy",
]
func = "setMaxMarketSize"
args = [
    "<%= settings.perpsKaitoMarketId %>",
    "<%= parseEther(settings.perpsKaitoMaxMarketSize) %>",
]
depends = [
    "invoke.createperpsKaitoMarket",
]

[invoke.setperpsKaitoMaxMarketSize.fromCall]
func = "owner"

[invoke.setperpsKaitoMaxMarketValue]
target = [
    "perpsFactory.PerpsMarketProxy",
]
func = "setMaxMarketValue"
args = [
    "<%= settings.perpsKaitoMarketId %>",
    "<%= parseEther(settings.perpsKaitoMaxMarketValue) %>",
]
depends = [
    "invoke.createperpsKaitoMarket",
]

[invoke.setperpsKaitoMaxMarketValue.fromCall]
func = "owner"

[invoke.setperpsKaitoMaxLiquidationParameters]
target = [
    "perpsFactory.PerpsMarketProxy",
]
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.perpsKaitoMarketId %>",
    "<%= parseEther(settings.perpsKaitoMaxLiquidationLimitAccumulationMultiplier) %>",
    "<%= settings.perpsKaitoMaxSecondsInLiquidationWindow %>",
    "<%= parseEther(settings.perpsKaitoMaxLiquidationPd) %>",
    "<%= settings.perpsKaitoEndorsedLiquidator %>",
]
depends = [
    "invoke.createperpsKaitoMarket",
]

[invoke.setperpsKaitoMaxLiquidationParameters.fromCall]
func = "owner"

[invoke.setperpsKaitoLiquidationParameters]
target = [
    "perpsFactory.PerpsMarketProxy",
]
func = "setLiquidationParameters"
args = [
    "<%= settings.perpsKaitoMarketId %>",
    "<%= parseEther(settings.perpsKaitoInitialMarginRatio) %>",
    "<%= parseEther(settings.perpsKaitoMinimumInitialMarginRatio) %>",
    "<%= parseEther(settings.perpsKaitoMaintenanceMarginScalar) %>",
    "<%= parseEther(settings.perpsKaitoFlagRewardRatioD18) %>",
    "<%= parseEther(settings.perpsKaitoMinimumPositionMargin) %>",
]
depends = [
    "invoke.createperpsKaitoMarket",
]

[invoke.setperpsKaitoLiquidationParameters.fromCall]
func = "owner"

[invoke.setperpsKaitoLockedOiRatio]
target = [
    "perpsFactory.PerpsMarketProxy",
]
func = "setLockedOiRatio"
args = [
    "<%= settings.perpsKaitoMarketId %>",
    "<%= parseEther(settings.perpsKaitoLockedOiRatio) %>",
]
depends = [
    "invoke.createperpsKaitoMarket",
]

[invoke.setperpsKaitoLockedOiRatio.fromCall]
func = "owner"

[invoke.setperpsKaitoLimitOrderFees]
target = [
    "perpsFactory.PerpsMarketProxy",
]
func = "setLimitOrderFees"
args = [
    "<%= settings.perpsKaitoMarketId %>",
    "<%= parseEther(settings.perpsKaitoLimitOrderMakerFeeRatio) %>",
    "<%= parseEther(settings.perpsKaitoLimitOrderTakerFeeRatio) %>",
]
depends = [
    "invoke.createperpsKaitoMarket",
]

[invoke.setperpsKaitoLimitOrderFees.fromCall]
func = "owner"
