[setting.perpsOndoFeedId]
defaultValue = "0xd40472610abe56d36d065a0cf889fc8f1dd9f3b7f2a478231a5fc6df07ea5ce3"

[setting.perpsOndoMarketId]
defaultValue = "3100"

[setting.perpsOndoSkewScale]
defaultValue = "<%= String(4_310_970) %>"

[setting.perpsOndoMaxFundingVelocity]
defaultValue = "24"

[setting.perpsOndoMakerFeeRatio]
defaultValue = "0.0004"

[setting.perpsOndoTakerFeeRatio]
defaultValue = "0.0006"

[setting.perpsOndoLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsOndoLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsOndoMaxMarketSize]
defaultValue = "<%= String(74_032) %>"

[setting.perpsOndoMaxMarketValue]
defaultValue = "<%= String(68_942) %>"

[setting.perpsOndoInitialMarginRatio]
defaultValue = "0.41666666666666413"

[setting.perpsOndoMaintenanceMarginScalar]
defaultValue = "0.29"

[setting.perpsOndoMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsOndoFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsOndoMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsOndoMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsOndoMinimumPositionMargin]
defaultValue = "25"

[setting.perpsOndoLockedOiRatio]
defaultValue = "0.5"

[setting.perpsOndoSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsOndoMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsOndoEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
