[setting.perpsPrclFeedId]
defaultValue = "0x5bbd1ce617792b476c55991c27cdfd89794f9f13356babc9c92405f5f0079683"

[setting.perpsPrclMarketId]
defaultValue = "6000"

[setting.perpsPrclSkewScale]
defaultValue = "<%= String(29_047_460) %>"

[setting.perpsPrclMaxFundingVelocity]
defaultValue = "24"

[setting.perpsPrclMakerFeeRatio]
defaultValue = "0.0005"

[setting.perpsPrclTakerFeeRatio]
defaultValue = "0.0008"

[setting.perpsPrclLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsPrclLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsPrclMaxMarketSize]
defaultValue = "<%= String(939041.18) %>"

[setting.perpsPrclMaxMarketValue]
defaultValue = "<%= String(87_756) %>"

[setting.perpsPrclInitialMarginRatio]
defaultValue = "0.6"

[setting.perpsPrclMaintenanceMarginScalar]
defaultValue = "0.28"

[setting.perpsPrclMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsPrclFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsPrclMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsPrclMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsPrclMinimumPositionMargin]
defaultValue = "25"

[setting.perpsPrclLockedOiRatio]
defaultValue = "0.5"

[setting.perpsPrclSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsPrclMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsPrclEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
