[setting.pythWifFeedId]
# https://pyth.network/developers/price-feed-ids
defaultValue = "0x4ca4beeca86f0d164160323817a4e42b10010a724c2217c6ee41b54cd4cc61fc"

[setting.wifPerpsMarketId]
defaultValue = "500"

[setting.perpsWifSkewScale]
defaultValue = "<%= String(37_000_000) %>"

[setting.perpsWifMaxFundingVelocity]
defaultValue = "24"

[setting.perpsWifLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsWifLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsWifMakerFeeRatio]
defaultValue = "0.0005"

[setting.perpsWifTakerFeeRatio]
defaultValue = "0.0008"

[setting.perpsWifMaxMarketSize]
defaultValue = "11750"

[setting.perpsWifMaxMarketValue]
defaultValue = "50000"

[setting.perpsWifInitialMarginRatio]
defaultValue = "5.99"

[setting.perpsWifMaintenanceMarginScalar]
defaultValue = "0.4"

[setting.perpsWifMinimumInitialMarginRatio]
defaultValue = "0.04"

[setting.perpsWifFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsWifMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsWifMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsWifMinimumPositionMargin]
defaultValue = "50"

[setting.perpsWifLockedOiRatio]
defaultValue = "0.5"

[setting.perpsWifSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsWifMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsWifEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
