[setting.perpsAixbtFeedId]
defaultValue = "0x0fc54579a29ba60a08fdb5c28348f22fd3bec18e221dd6b90369950db638a5a7"

[setting.perpsAixbtMarketId]
defaultValue = "5600"

[setting.perpsAixbtSkewScale]
defaultValue = "<%= String(18_320_220) %>"

[setting.perpsAixbtMaxFundingVelocity]
defaultValue = "24"

[setting.perpsAixbtMakerFeeRatio]
defaultValue = "0.0005"

[setting.perpsAixbtTakerFeeRatio]
defaultValue = "0.0008"

[setting.perpsAixbtLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsAixbtLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsAixbtMaxMarketSize]
defaultValue = "<%= String(502_642) %>"

[setting.perpsAixbtMaxMarketValue]
defaultValue = "<%= String(54_874) %>"

[setting.perpsAixbtInitialMarginRatio]
defaultValue = "0.03810203344179687"

[setting.perpsAixbtMaintenanceMarginScalar]
defaultValue = "0.28"

[setting.perpsAixbtMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsAixbtFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsAixbtMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsAixbtMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsAixbtMinimumPositionMargin]
defaultValue = "25"

[setting.perpsAixbtLockedOiRatio]
defaultValue = "0.5"

[setting.perpsAixbtSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsAixbtMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsAixbtEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
