[setting.perpsAptFeedId]
defaultValue = "0x03ae4db29ed4ae33d323568895aa00337e658e348b37509f5372ae51f0af00d5"

[setting.perpsAptMarketId]
defaultValue = "6100"

[setting.perpsAptSkewScale]
defaultValue = "<%= String(1_137_863) %>"

[setting.perpsAptMaxFundingVelocity]
defaultValue = "24"

[setting.perpsAptMakerFeeRatio]
defaultValue = "0.0005"

[setting.perpsAptTakerFeeRatio]
defaultValue = "0.0008"

[setting.perpsAptLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsAptLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsAptMaxMarketSize]
defaultValue = "<%= String(19207.98) %>"

[setting.perpsAptMaxMarketValue]
defaultValue = "<%= String(96_825) %>"

[setting.perpsAptInitialMarginRatio]
defaultValue = "0.2920867964332497"

[setting.perpsAptMaintenanceMarginScalar]
defaultValue = "0.317"

[setting.perpsAptMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsAptFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsAptMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsAptMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsAptMinimumPositionMargin]
defaultValue = "50"

[setting.perpsAptLockedOiRatio]
defaultValue = "0.5"

[setting.perpsAptSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsAptMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsAptEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
