[setting.pythAvaxFeedId]
defaultValue = "0x93da3352f9f1d105fdfe4971cfa80e9dd777bfc5d0f683ebb6e1294b92137bb7"

[setting.perpsAvaxMarketId]
defaultValue = "1700"

[setting.perpsAvaxSkewScale]
defaultValue = "<%= String(1_500_000) %>"

[setting.perpsAvaxMaxFundingVelocity]
defaultValue = "24"

[setting.perpsAvaxLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsAvaxLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsAvaxMakerFeeRatio]
defaultValue = "0.0005"

[setting.perpsAvaxTakerFeeRatio]
defaultValue = "0.0008"

[setting.perpsAvaxMaxMarketSize]
defaultValue = "<%= String(6160.63) %>"

[setting.perpsAvaxMaxMarketValue]
defaultValue = "<%= String(137_035) %>"

[setting.perpsAvaxInitialMarginRatio]
defaultValue = "9.08"

[setting.perpsAvaxMaintenanceMarginScalar]
defaultValue = "0.36"

[setting.perpsAvaxMinimumInitialMarginRatio]
defaultValue = "0.02"

[setting.perpsAvaxFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsAvaxMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsAvaxMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsAvaxMinimumPositionMargin]
defaultValue = "50"

[setting.perpsAvaxLockedOiRatio]
defaultValue = "0.5"

[setting.perpsAvaxSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsAvaxMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsAvaxEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
