[setting.pythBtcFeedId]
defaultValue = "0xe62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43"

[setting.btcPerpsMarketId]
defaultValue = "200"

[setting.perpsBtcSkewScale]
defaultValue = "<%= String(20_000) %>"

[setting.perpsBtcMaxFundingVelocity]
defaultValue = "9"

[setting.perpsBtcLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsBtcLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsBtcMakerFeeRatio]
defaultValue = "0.0005"

[setting.perpsBtcTakerFeeRatio]
defaultValue = "0.0008"

[setting.perpsBtcMaxMarketSize]
defaultValue = "<%= String(12.58) %>"

[setting.perpsBtcMaxMarketValue]
defaultValue = "<%= String(1_240_000) %>"

[setting.perpsBtcInitialMarginRatio]
defaultValue = "1.54"

[setting.perpsBtcMaintenanceMarginScalar]
defaultValue = "0.28"

[setting.perpsBtcMinimumInitialMarginRatio]
defaultValue = "0.02"

[setting.perpsBtcFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsBtcMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsBtcMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsBtcMinimumPositionMargin]
defaultValue = "50"

[setting.perpsBtcLockedOiRatio]
defaultValue = "0.5"

[setting.perpsBtcSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsBtcMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsBtcEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"
