[setting.pythDogeFeedId]
defaultValue = "0xdcef50dd0a4cd2dcc17e45df1676dcb336a11a61c69df7a0299b0150c672d25c"

[setting.dogePerpsMarketId]
defaultValue = "1300"

[setting.perpsDogeSkewScale]
defaultValue = "<%= String(750_000_000) %>"

[setting.perpsDogeMaxFundingVelocity]
defaultValue = "24"

[setting.perpsDogeLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsDogeLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsDogeMakerFeeRatio]
defaultValue = "0.0005"

[setting.perpsDogeTakerFeeRatio]
defaultValue = "0.0008"

[setting.perpsDogeMaxMarketSize]
defaultValue = "<%= String(309257.44) %>"

[setting.perpsDogeMaxMarketValue]
defaultValue = "<%= String(101_495) %>"

[setting.perpsDogeInitialMarginRatio]
defaultValue = "6.9"

[setting.perpsDogeMaintenanceMarginScalar]
defaultValue = "0.3"

[setting.perpsDogeMinimumInitialMarginRatio]
defaultValue = "0.02"

[setting.perpsDogeFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsDogeMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsDogeMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsDogeMinimumPositionMargin]
defaultValue = "50"

[setting.perpsDogeLockedOiRatio]
defaultValue = "0.5"

[setting.perpsDogeSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsDogeMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsDogeEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
