[setting.pythEnaFeedId]
# https://pyth.network/developers/price-feed-ids
defaultValue = "0xb7910ba7322db020416fcac28b48c01212fd9cc8fbcbaf7d30477ed8605f6bd4"

[setting.enaPerpsMarketId]
defaultValue = "1200"

[setting.perpsEnaSkewScale]
defaultValue = "<%= String(10_000_000) %>"

[setting.perpsEnaMaxFundingVelocity]
defaultValue = "36"

[setting.perpsEnaMakerFeeRatio]
defaultValue = "0.0005"

[setting.perpsEnaTakerFeeRatio]
defaultValue = "0.0008"

[setting.perpsEnaMaxMarketSize]
defaultValue = "514000"

[setting.perpsEnaMaxMarketValue]
defaultValue = "500000"

[setting.perpsEnaInitialMarginRatio]
defaultValue = "3.46"

[setting.perpsEnaMaintenanceMarginScalar]
defaultValue = "0.38"

[setting.perpsEnaMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsEnaFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsEnaMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsEnaMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsEnaMinimumPositionMargin]
defaultValue = "50"

[setting.perpsEnaLockedOiRatio]
defaultValue = "0.5"

[setting.perpsEnaSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsEnaMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsEnaEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
