[setting.settlementReward]
defaultValue = "0.1"

[setting.perps_keeper_l1_cost_settle_gas_units]
defaultValue = "<%= String(40_000) %>"

[setting.perps_keeper_l2_cost_settle_gas_units]
defaultValue = "<%= String(11_000_000) %>"

[setting.perps_keeper_l1_cost_flag_gas_units]
defaultValue = "<%= String(62_000) %>"

[setting.perps_keeper_l2_cost_flag_gas_units]
defaultValue = "<%= String(2_320_000) %>"

[setting.perps_keeper_l1_cost_liquidate_gas_units]
defaultValue = "<%= String(20_000) %>"

[setting.perps_keeper_l2_cost_liquidate_gas_units]
defaultValue = "<%= String(2_000_000) %>"

[setting.perps_keeper_settle_tx_size]
defaultValue = "<%= String(3_600) %>"

[setting.perps_keeper_flag_tx_size]
defaultValue = "<%= String(3_000) %>"

[setting.perps_keeper_liquidate_tx_size]
defaultValue = "<%= String(1_800) %>"

[setting.perps_liquidation_min_keeper_reward_usd]
defaultValue = "7.5"

[setting.perps_liquidation_min_keeper_profit_ratio_d18]
defaultValue = "0.30"

[setting.perps_liquidation_max_keeper_reward_usd]
defaultValue = "100"

[setting.perps_liquidation_max_keeper_scaling_ratio_d18]
defaultValue = "0.3"

[setting.perps_low_util_gradient]
defaultValue = "0"

[setting.perps_gradient_breakpoint]
defaultValue = "0"

[setting.perps_high_util_gradient]
defaultValue = "0"

[setting.commit_fee_receiver]
defaultValue = "0x66E1C0734A6e1351F7401219E4Ec9CF6a91a50cd"

[invoke.setPerpsLiquidationRewardGuards]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setKeeperRewardGuards"
args = [
    "<%= parseEther(settings.perps_liquidation_min_keeper_reward_usd) %>",
    "<%= parseEther(settings.perps_liquidation_min_keeper_profit_ratio_d18) %>",
    "<%= parseEther(settings.perps_liquidation_max_keeper_reward_usd) %>",
    "<%= parseEther(settings.perps_liquidation_max_keeper_scaling_ratio_d18) %>",
]
depends = ["provision.perpsFactory"]

[invoke.setPerpsSynthDeductionPriority]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSynthDeductionPriority"
args = [["0"]]
depends = ["provision.perpsFactory"]

[invoke.setPerAccountCapsPerps]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setPerAccountCaps"
args = ["30", "7"]
depends = ["provision.perpsFactory"]

[invoke.setPerpsMarketKeeperCostNodeId]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updateKeeperCostNodeId"
args = ["<%= extras.perps_keeper_cost_usd_oracle_id %>"]
depends = [
    "provision.perpsFactory",
    "invoke.registerPerps_KeeperCostUsdOracleNode",
]

[invoke.setInterestRateParams]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setInterestRateParameters"
args = [
    "<%= parseEther(settings.perps_low_util_gradient) %>",
    "<%= parseEther(settings.perps_gradient_breakpoint) %>",
    "<%= parseEther(settings.perps_high_util_gradient) %>",
]
depends = ["provision.perpsFactory"]

[invoke.setCommitFeeReceiver]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setcommitFeeReciever"
args = ["<%= settings.commit_fee_receiver %>"]
depends = ["provision.perpsFactory"]
