[setting.perpsHypeFeedId]
defaultValue = "0x4279e31cc369bbcc2faf022b382b080e32a8e689ff20fbc530d2a603eb6cd98b"

[setting.perpsHypeMarketId]
defaultValue = "2200"

[setting.perpsHypeSkewScale]
defaultValue = "<%= String(40_000) %>"

[setting.perpsHypeMaxFundingVelocity]
defaultValue = "24"

[setting.perpsHypeMakerFeeRatio]
defaultValue = "0.0004"

[setting.perpsHypeTakerFeeRatio]
defaultValue = "0.0006"

[setting.perpsHypeLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsHypeLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsHypeMaxMarketSize]
defaultValue = "<%= String(8_398) %>"

[setting.perpsHypeMaxMarketValue]
defaultValue = "<%= String(300_000) %>"

[setting.perpsHypeInitialMarginRatio]
defaultValue = "1.5277777777777772"

[setting.perpsHypeMaintenanceMarginScalar]
defaultValue = "0.28"

[setting.perpsHypeMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsHypeFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsHypeMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsHypeMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsHypeMinimumPositionMargin]
defaultValue = "25"

[setting.perpsHypeLockedOiRatio]
defaultValue = "0.5"

[setting.perpsHypeSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsHypeMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsHypeEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
