[setting.perpsIpFeedId]
defaultValue = "0xb620ba83044577029da7e4ded7a2abccf8e6afc2a0d4d26d89ccdd39ec109025"

[setting.perpsIpMarketId]
defaultValue = "3900"

[setting.perpsIpSkewScale]
defaultValue = "<%= String(600_000) %>"

[setting.perpsIpMaxFundingVelocity]
defaultValue = "24"

[setting.perpsIpMakerFeeRatio]
defaultValue = "0.0004"

[setting.perpsIpTakerFeeRatio]
defaultValue = "0.0006"

[setting.perpsIpLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsIpLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsIpMaxMarketSize]
defaultValue = "<%= String(13_620) %>"

[setting.perpsIpMaxMarketValue]
defaultValue = "<%= String(80_000) %>"

[setting.perpsIpInitialMarginRatio]
defaultValue = "0.3472222222222201"

[setting.perpsIpMaintenanceMarginScalar]
defaultValue = "0.26"

[setting.perpsIpMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsIpFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsIpMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsIpMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsIpMinimumPositionMargin]
defaultValue = "25"

[setting.perpsIpLockedOiRatio]
defaultValue = "0.5"

[setting.perpsIpSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsIpMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsIpEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
