include = [
    "../../oracles/pyth-pepe.toml",
    "../../markets/common/bigcap-settings.toml",
]

[setting.pepePerpsMarketId]

[setting.perpsPepeSkewScale]

[setting.perpsPepeMaxFundingVelocity]

[setting.perpsPepeMakerFeeRatio]

[setting.perpsPepeTakerFeeRatio]

[setting.perpsPepeMaxMarketSize]

[setting.perpsPepeInitialMarginRatio]

[setting.perpsPepeMaintenanceMarginFraction]

[setting.perpsPepeFlagRewardRatioD18]

[setting.perpsPepeMaxLiquidationLimitAccumulationMultiplier]

[setting.perpsPepeMaxSecondsInLiquidationWindow]

[setting.perpsPepeMaxLiquidationPd]

[setting.perpsPepeEndorsedLiquidator]

[setting.perpsPepeMinimumPositionMargin]

[setting.perpsPepeLockedOiRatio]

[invoke.createPepePerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "createMarket"
args = ["<%= settings.pepePerpsMarketId %>", "Pepe", "PEPE"]
depends = ["provision.system", "provision.perpsFactory"]

[invoke.setPerpsPricePepe]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updatePriceData"
args = [
    "<%= settings.pepePerpsMarketId %>",
    "<%= extras.pepe_oracle_id %>",
    "<%= settings.bigCapStrictStalenessTolerance %>",
]
depends = ["invoke.createPepePerpsMarket"]

# Do not modify this step. Edit [invoke.setPerpsPepeSettlementStrategy] instead.
[invoke.addPerpsPepeSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "addSettlementStrategy"
args = [
    "<%= settings.pepePerpsMarketId %>",
    { strategyType = "0", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", settlementReward = "0", disabled = false, commitmentPriceDelay = "0" },
]
extra.pepe_pyth_settlement_strategy.event = "SettlementStrategyAdded"
extra.pepe_pyth_settlement_strategy.arg = 2
depends = ["invoke.createPepePerpsMarket"]

[invoke.setPerpsPepeSettlementStrategy]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setSettlementStrategy"
args = [
    "<%= settings.pepePerpsMarketId %>",
    "<%= extras.pepe_pyth_settlement_strategy %>",                                                                                                                                                                                                                                                                                                                                                                                      # Settlement Strategy ID
    { strategyType = "0", settlementDelay = "<%= settings.bigCapSettlementDelay %>", settlementWindowDuration = "<%= settings.bigCapSettlementWindowDuration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pythPepeFeedId %>", settlementReward = "<%= parseEther(settings.settlementReward) %>", disabled = false, commitmentPriceDelay = "2" },
]
depends = [
    'provision.perpsFactory',
    'setting.pepePerpsMarketId',
    'invoke.addPerpsPepeSettlementStrategy',
    'provision.pyth_erc7412_wrapper',
    'setting.bigCapSettlementDelay',
    'setting.bigCapSettlementWindowDuration',
    'setting.pythPepeFeedId',
    'setting.settlementReward',
]

[invoke.setPerpsPepeFundingParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setFundingParameters"
args = [
    "<%= settings.pepePerpsMarketId %>",
    "<%= parseEther(settings.perpsPepeSkewScale) %>",
    "<%= parseEther(settings.perpsPepeMaxFundingVelocity) %>",
]
depends = ["invoke.createPepePerpsMarket"]

[invoke.setPerpsPepeOrderFees]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setOrderFees"
args = [
    "<%= settings.pepePerpsMarketId %>",
    "<%= parseEther(settings.perpsPepeMakerFeeRatio) %>",
    "<%= parseEther(settings.perpsPepeTakerFeeRatio) %>",
]
depends = ["invoke.createPepePerpsMarket"]

[invoke.setPerpsPepeMaxMarketSize]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketSize"
args = [
    "<%= settings.pepePerpsMarketId %>",
    "<%= parseEther(settings.perpsPepeMaxMarketSize) %>",
]
depends = ["invoke.createPepePerpsMarket"]

[invoke.setPerpsPepeMaxMarketValue]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxMarketValue"
args = [
    "<%= settings.pepePerpsMarketId %>",
    "<%= parseEther(settings.perpsPepeMaxMarketValue) %>",
]
depends = ["invoke.createPepePerpsMarket"]

[invoke.setPerpsPepeMaxLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setMaxLiquidationParameters"
args = [
    "<%= settings.pepePerpsMarketId %>",
    "<%= parseEther(settings.perpsPepeMaxLiquidationLimitAccumulationMultiplier) %>",
    "<%= settings.perpsPepeMaxSecondsInLiquidationWindow %>",
    "<%= parseEther(settings.perpsPepeMaxLiquidationPd) %>",
    "<%= settings.perpsPepeEndorsedLiquidator %>",
]
depends = ["invoke.createPepePerpsMarket"]

[invoke.setPerpsPepeLiquidationParameters]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLiquidationParameters"
args = [
    "<%= settings.pepePerpsMarketId %>",
    "<%= parseEther(settings.perpsPepeInitialMarginRatio) %>",
    "<%= parseEther(settings.perpsPepeMinimumInitialMarginRatio) %>",
    "<%= parseEther(settings.perpsPepeMaintenanceMarginScalar) %>",
    "<%= parseEther(settings.perpsPepeFlagRewardRatioD18) %>",
    "<%= parseEther(settings.perpsPepeMinimumPositionMargin) %>",
]
depends = ["invoke.createPepePerpsMarket"]

[invoke.setPerpsPepeLockedOiRatio]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setLockedOiRatio"
args = [
    "<%= settings.pepePerpsMarketId %>",
    "<%= parseEther(settings.perpsPepeLockedOiRatio) %>",
]
depends = ["invoke.createPepePerpsMarket"]
