[setting.referrerFee]
defaultValue = "<%= parseEther('0.4') %>"

[invoke.setPolynomialAsReferrerOnPerpsMarket]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "updateReferrerShare"
args = [
    "0x66E1C0734A6e1351F7401219E4Ec9CF6a91a50cd",
    "<%= settings.referrerFee %>",
]
depends = ["provision.perpsFactory"]
