[setting.perpsStxFeedId]
defaultValue = "0xec7a775f46379b5e943c3526b1c8d54cd49749176b0b98e02dde68d1bd335c17"

[setting.perpsStxMarketId]
defaultValue = "5900"

[setting.perpsStxSkewScale]
defaultValue = "<%= String(4_059_380) %>"

[setting.perpsStxMaxFundingVelocity]
defaultValue = "24"

[setting.perpsStxMakerFeeRatio]
defaultValue = "0.0005"

[setting.perpsStxTakerFeeRatio]
defaultValue = "0.0008"

[setting.perpsStxLimitOrderMakerFeeRatio]
defaultValue = "0.0001"

[setting.perpsStxLimitOrderTakerFeeRatio]
defaultValue = "0.0002"

[setting.perpsStxMaxMarketSize]
defaultValue = "<%= String(86_153) %>"

[setting.perpsStxMaxMarketValue]
defaultValue = "<%= String(57_268) %>"

[setting.perpsStxInitialMarginRatio]
defaultValue = "0.01018352705034401"

[setting.perpsStxMaintenanceMarginScalar]
defaultValue = "0.26"

[setting.perpsStxMinimumInitialMarginRatio]
defaultValue = "0.05"

[setting.perpsStxFlagRewardRatioD18]
defaultValue = "0.0003"

[setting.perpsStxMaxLiquidationLimitAccumulationMultiplier]
defaultValue = "1.5"

[setting.perpsStxMaxSecondsInLiquidationWindow]
defaultValue = "30"

[setting.perpsStxMinimumPositionMargin]
defaultValue = "25"

[setting.perpsStxLockedOiRatio]
defaultValue = "0.5"

[setting.perpsStxSynthMaxCollateralAmount]
defaultValue = "<%= MaxUint256 %>"

[setting.perpsStxMaxLiquidationPd]
defaultValue = "0.0005"

[setting.perpsStxEndorsedLiquidator]
defaultValue = "0x38D4200767628f4197C5d5FdDA24927C28dDadeF"

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"
