[setting.sdai_issuance_ratio]
defaultValue = "<%= MaxUint256 %>"

[setting.sdai_liquidation_ratio]
defaultValue = "<%= parseEther('1.02') %>"

[setting.sdai_liquidation_reward]
defaultValue = "<%= parseEther('1') %>"

[setting.sdai_min_delegation]
defaultValue = "<%= parseEther('100') %>"

[setting.sdai_token_address]
defaultValue = "0x5781aF1672e267De8802ADc89f6D56b2657B2a13"