[setting.SUSDE_issuance_ratio]
defaultValue = "<%= MaxUint256 %>"

[setting.SUSDE_liquidation_ratio]
defaultValue = "<%= parseEther('1.2') %>"

[setting.SUSDE_liquidation_reward]
defaultValue = "<%= parseEther('1') %>"

[setting.SUSDE_min_delegation]
defaultValue = "<%= parseEther('100') %>"

[setting.SUSDE_token_address]
defaultValue = "0xeC0B73C94a38F1cBE9eEb7feF88A8CeE8d877b3a"