[invoke.set_deniers_core_withdraw]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setDeniers"
args = [
    "<%= formatBytes32String('withdraw') %>",
    [
        "0x9f76043B23125024Ce5f0Fb4AE707482107dd2a8",
        "0x2b02AAd6f1694E7D9c934B7b3Ec444541286cF0f",
    ],
]
depends = ["provision.system"]

[invoke.set_deniers_perps]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setDeniers"
args = [
    "<%= formatBytes32String('perpsSystem') %>",
    [
        "0x9f76043B23125024Ce5f0Fb4AE707482107dd2a8",
        "0x2b02AAd6f1694E7D9c934B7b3Ec444541286cF0f",
    ],
]
depends = ["provision.system"]