[setting.fxCbBtcMaxMarketCollateral]
defaultValue = "<%= parseEther(String(250)) %>"

[setting.fxCbBtcSkewScale]
defaultValue = "<%= parseEther(String(35_000)) %>"

[setting.spotStrictStalenessTolerance]
defaultValue = "300"

[setting.pyth_feed_id_cbbtc]
defaultValue = "0x2817d7bfe5c64b8ea956e9a26f573ef64e72e4d7891f2d6af9bcc93f7aff9a97"

[setting.pyth_feed_url_cbbtc]
defaultValue = "https://hermes.pyth.network/v2/updates/price/latest?ids[]=<%= settings.pyth_feed_id_cbbtc %>"

[setting.cbbtc_address]
defaultValue = "0x7B1C847ED0B889ED466DE069c0114a2d92f2944A"

[invoke.createCbBtcSynth]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "owner"
func = "createSynth"
args = ["Polynomial Coinbase Wrapped BTC", "fxCbBTC", "<%= settings.owner %>"]
extra.fx_cbbtc_market_id.event = "SynthRegistered"
extra.fx_cbbtc_market_id.arg = 0
extra.fx_cbbtc_token_address.event = "SynthRegistered"
extra.fx_cbbtc_token_address.arg = 1

[invoke.setSynthPriceCbBtc]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_cbbtc_market_id %>"]
func = "updatePriceData"
args = [
    "<%= extras.fx_cbbtc_market_id %>",
    "<%= extras.cbbtc_oracle_id %>",
    "<%= extras.cbbtc_oracle_id %>",
    "<%= settings.spotStrictStalenessTolerance %>",
]

[invoke.setSynthMaxMarketCollateralCbBtc]
target = ["system.CoreProxy"]
fromCall.func = "owner"
fromCall.args = []
func = "configureMaximumMarketCollateral"
args = [
    "<%= extras.fx_cbbtc_market_id %>",
    "<%= settings.cbbtc_address %>",
    "<%= settings.fxCbBtcMaxMarketCollateral %>",
]

[invoke.setSkewScaleCbBtc]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_cbbtc_market_id %>"]
func = "setMarketSkewScale"
args = ["<%= extras.fx_cbbtc_market_id %>", "<%= settings.fxCbBtcSkewScale %>"]


[invoke.configureSynthWrapperCbBtc]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_cbbtc_market_id %>"]
func = "setWrapper"
args = [
    "<%= extras.fx_cbbtc_market_id %>",
    "<%= settings.cbbtc_address %>",
    "<%= settings.fxCbBtcMaxMarketCollateral %>",
]

# NOTE set disabled = true to addSettlementStrategy call before initial mainnet deployment
[invoke.SpotMarketProxy_addSettlementStrategy_cbbtc]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_cbbtc_market_id %>"]
func = "addSettlementStrategy"
args = [
    "<%= extras.fx_cbbtc_market_id %>",
    { strategyType = "1", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", url = "", settlementReward = 0, minimumUsdExchangeAmount = "0", maxRoundingLoss = "1", priceDeviationTolerance = "0", disabled = false },
]
extra.fx_cbbtc_settlement_strategy_id.event = "SettlementStrategyAdded"
extra.fx_cbbtc_settlement_strategy_id.arg = 1

[invoke.SpotMarketProxy_setSettlementStrategy_fxCbBtc]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_cbbtc_market_id %>"]
func = "setSettlementStrategy"
args = [
    "<%= extras.fx_cbbtc_market_id %>",
    "<%= extras.fx_cbbtc_settlement_strategy_id %>",
    { strategyType = "1", settlementDelay = "<%= settings.big_cap_settlement_delay %>", settlementWindowDuration = "<%= settings.big_cap_settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_cbbtc %>", url = "<%= settings.pyth_feed_url_cbbtc %>", settlementReward = "<%= settings.settlement_reward %>", minimumUsdExchangeAmount = "<%= settings.settlement_minimum_usd_exchange_amount %>", maxRoundingLoss = "<%= settings.settlement_max_rounding_loss %>", priceDeviationTolerance = "<%= settings.price_deviation_tolerance %>", disabled = true },
]

[invoke.SpotMarketProxy_setAtomicFixedFee_fxCbBtc]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_cbbtc_market_id %>"]
func = "setAtomicFixedFee"
args = ["<%= extras.fx_cbbtc_market_id %>", "<%= parseEther(String(0.02)) %>"]

[invoke.configure_cbbtc_collateral]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "configureCollateral"  # "args" see below in the multiline block

[[invoke.configure_cbbtc_collateral.args]]
tokenAddress = "<%= settings.cbbtc_address %>"
oracleNodeId = "<%= extras.cbbtc_oracle_id %>"
issuanceRatioD18 = "<%= parseEther('2') %>"
liquidationRatioD18 = "<%= parseEther('1.1') %>"
liquidationRewardD18 = "<%= parseEther('0.0001') %>"
minDelegationD18 = "<%= parseEther('0.1') %>"
depositingEnabled = false

[invoke.configure_fxcbbtc_collateral]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "configureCollateral"  # "args" see below in the multiline block

[[invoke.configure_fxcbbtc_collateral.args]]
tokenAddress = "<%= extras.fx_cbbtc_token_address %>"
oracleNodeId = "<%= extras.cbbtc_oracle_id %>"
issuanceRatioD18 = "<%= parseEther('2') %>"
liquidationRatioD18 = "<%= parseEther('1.1') %>"
liquidationRewardD18 = "<%= parseEther('0.0001') %>"
minDelegationD18 = "<%= parseEther('0.1') %>"
depositingEnabled = false
