[setting.big_cap_settlement_delay]
defaultValue = "60"

[setting.big_cap_settlement_window_duration]
defaultValue = "60"

[setting.settlement_reward]
defaultValue = "<%= parseEther('1') %>"

[setting.settlement_minimum_usd_exchange_amount]
defaultValue = "<%= parseEther('0.000001') %>"

[setting.settlement_max_rounding_loss]
defaultValue = "<%= parseEther('0.000001') %>"

[setting.price_deviation_tolerance]
defaultValue = "<%= parseEther('1') %>"
