[setting.fxUsdsMaxMarketCollateral]
defaultValue = "<%= parseEther(String(10_000_000)) %>"

[setting.fxUsdsSkewScale]
defaultValue = "<%= parseEther(String(0)) %>"

[setting.spotStrictStalenessTolerance]
defaultValue = "300"

[setting.pyth_feed_id_usds]
defaultValue = "0x77f0971af11cc8bac224917275c1bf55f2319ed5c654a1ca955c82fa2d297ea1"

[setting.pyth_feed_url_usds]
defaultValue = "https://hermes.pyth.network/v2/updates/price/latest?ids[]=<%= settings.pyth_feed_id_usds %>"

[setting.usds_address]
defaultValue = "0xfFe0837E4885849C9FBFd8FefE5CA4FC7AdC56c9"

[invoke.createUsdsSynth]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "owner"
func = "createSynth"
args = ["Polynomial USDS Stablecoin", "fxUSDS", "<%= settings.owner %>"]
extra.fx_usds_market_id.event = "SynthRegistered"
extra.fx_usds_market_id.arg = 0
extra.fx_usds_token_address.event = "SynthRegistered"
extra.fx_usds_token_address.arg = 1

[invoke.setSynthPriceUsds]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_usds_market_id %>"]
func = "updatePriceData"
args = [
    "<%= extras.fx_usds_market_id %>",
    "<%= extras.usds_oracle_id %>",
    "<%= extras.usds_oracle_id %>",
    "<%= settings.spotStrictStalenessTolerance %>",
]

[invoke.setSynthMaxMarketCollateralUsds]
target = ["system.CoreProxy"]
fromCall.func = "owner"
fromCall.args = []
func = "configureMaximumMarketCollateral"
args = [
    "<%= extras.fx_usds_market_id %>",
    "<%= settings.usds_address %>",
    "<%= settings.fxUsdsMaxMarketCollateral %>",
]

[invoke.setSkewScaleUsds]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_usds_market_id %>"]
func = "setMarketSkewScale"
args = ["<%= extras.fx_usds_market_id %>", "<%= settings.fxUsdsSkewScale %>"]


[invoke.configureSynthWrapperUsds]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_usds_market_id %>"]
func = "setWrapper"
args = [
    "<%= extras.fx_usds_market_id %>",
    "<%= settings.usds_address %>",
    "<%= settings.fxUsdsMaxMarketCollateral %>",
]

# NOTE set disabled = true to addSettlementStrategy call before initial mainnet deployment
[invoke.SpotMarketProxy_addSettlementStrategy_usds]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_usds_market_id %>"]
func = "addSettlementStrategy"
args = [
    "<%= extras.fx_usds_market_id %>",
    { strategyType = "1", settlementDelay = "0", settlementWindowDuration = "1", priceVerificationContract = "0x0000000000000000000000000000000000000000", feedId = "0x0000000000000000000000000000000000000000000000000000000000000000", url = "", settlementReward = 0, minimumUsdExchangeAmount = "0", maxRoundingLoss = "1", priceDeviationTolerance = "0", disabled = false },
]
extra.fx_usds_settlement_strategy_id.event = "SettlementStrategyAdded"
extra.fx_usds_settlement_strategy_id.arg = 1

[invoke.SpotMarketProxy_setSettlementStrategy_fxUsds]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_usds_market_id %>"]
func = "setSettlementStrategy"
args = [
    "<%= extras.fx_usds_market_id %>",
    "<%= extras.fx_usds_settlement_strategy_id %>",
    { strategyType = "1", settlementDelay = "<%= settings.big_cap_settlement_delay %>", settlementWindowDuration = "<%= settings.big_cap_settlement_window_duration %>", priceVerificationContract = "<%= imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address %>", feedId = "<%= settings.pyth_feed_id_usds %>", url = "<%= settings.pyth_feed_url_usds %>", settlementReward = "<%= settings.settlement_reward %>", minimumUsdExchangeAmount = "<%= settings.settlement_minimum_usd_exchange_amount %>", maxRoundingLoss = "<%= settings.settlement_max_rounding_loss %>", priceDeviationTolerance = "<%= settings.price_deviation_tolerance %>", disabled = true },
]

[invoke.SpotMarketProxy_setAtomicFixedFee_fxUsds]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.fx_usds_market_id %>"]
func = "setAtomicFixedFee"
args = ["<%= extras.fx_usds_market_id %>", "<%= parseEther(String(0.001)) %>"]

[invoke.configure_usds_collateral]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "configureCollateral"  # "args" see below in the multiline block

[[invoke.configure_usds_collateral.args]]
tokenAddress = "<%= settings.usds_address %>"
oracleNodeId = "<%= extras.usds_oracle_id %>"
issuanceRatioD18 = "<%= parseEther('2') %>"
liquidationRatioD18 = "<%= parseEther('1.1') %>"
liquidationRewardD18 = "<%= parseEther('0.0001') %>"
minDelegationD18 = "<%= parseEther('0.1') %>"
depositingEnabled = false

[invoke.configure_fxusds_collateral]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "configureCollateral"  # "args" see below in the multiline block

[[invoke.configure_fxusds_collateral.args]]
tokenAddress = "<%= extras.fx_usds_token_address %>"
oracleNodeId = "<%= extras.usds_oracle_id %>"
issuanceRatioD18 = "<%= parseEther('2') %>"
liquidationRatioD18 = "<%= parseEther('1.1') %>"
liquidationRewardD18 = "<%= parseEther('0.0001') %>"
minDelegationD18 = "<%= parseEther('0.1') %>"
depositingEnabled = false
