name = "polynomial-mainnet"
version = "1"
description = "Andromeda dev deployment"
preset = "main"
include = [
    "tomls/core.toml",                                         # Provision the core system
    "tomls/settings.toml",                                     # Apply minimum liquidity ratio and withdrawal timeout
    "tomls/permissions.toml",                                  # Allow deployer to create pools
    "tomls/permit-deniers.toml",                               # Add feature flag deniers to perps and core systems
    "tomls/pools/main-pool.toml",                              # Create Main Pool
    "tomls/markets/spot-factory.toml",
    "tomls/markets/perps-factory.toml",
    "tomls/markets/common/bigcap-settings.toml",
    "tomls/polynomial-mainnet-andromeda/spot/usdc.toml",       # sUSDC spot market/wrapper, mock for USDC
    "tomls/permit-all-perps-perpsSystem.toml",                 # Enable perps market
    "tomls/polynomial-mainnet-andromeda/perps/referrers.toml",
    "tomls/polynomial-mainnet-andromeda/perps/global.toml",    # Global perps settings
    "tomls/oracles/perps-keeper-cost.toml",                    # Add gas oracle for keeper fees
    # "tomls/blast-sepolia-andromeda/perps/feeCollector.toml",
    # Collaterals
    "tomls/polynomial-mainnet-andromeda/collaterals/susdc.toml",
    "tomls/collaterals/susdc.toml",
    "tomls/polynomial-mainnet-andromeda/collaterals/sdai.toml",
    "tomls/oracles/pyth-sdai.toml",
    "tomls/oracles/pyth-usdc.toml",
    "tomls/oracles/sdai.toml",
    "tomls/collaterals/sdai.toml",
    "tomls/polynomial-mainnet-andromeda/collaterals/susde.toml",
    "tomls/oracles/pyth-susde.toml",
    "tomls/oracles/susde.toml",
    "tomls/collaterals/susde.toml",
    # BTC
    "tomls/polynomial-mainnet-andromeda/perps/btc-invokes.toml",
    "tomls/oracles/pyth-btc.toml",
    "tomls/polynomial-mainnet-andromeda/perps/btc.toml",
    # ETH
    "tomls/polynomial-mainnet-andromeda/perps/eth-invokes.toml",
    "tomls/oracles/pyth-eth.toml",
    "tomls/polynomial-mainnet-andromeda/perps/eth.toml",
]

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"

[setting.snx_package]
defaultValue = "polynomial-core:3.4.2"

[setting.perps_keeper_cost_package]
defaultValue = "fx-op-gas-price-oracle:3.4.0"

[setting.spot_market_package]
defaultValue = "fx-spot-market:3.4.2"

[setting.perps_market_package]
defaultValue = "fx-perps-market:3.4.2"

# [setting.buyback_snx_package]
# defaultValue = "buyback-snx:3.3.14" # Do not update! This package isn't upgradeable. A version change will deploy a new contract.

[setting.salt]
defaultValue = "andromeda-dev"

[setting.target_preset]
defaultValue = "main" # Preset assigned to provisioned packages

[setting.pyth_price_verification_address]
# https://docs.pyth.network/documentation/pythnet-price-feeds/evm
defaultValue = "0x2880aB155794e7179c9eE2e38200202908C17B43"

[provision.pyth_erc7412_wrapper]
source = "fx-pyth-erc7412-wrapper:3.4.0"
targetPreset = "<%= settings.target_preset %>"
options.salt = "<%= settings.salt %>"
options.pythAddress = "<%= settings.pyth_price_verification_address %>"

[setting.owner]
defaultValue = "0x9f76043B23125024Ce5f0Fb4AE707482107dd2a8"

[setting.deployer]
defaultValue = "0x9f76043B23125024Ce5f0Fb4AE707482107dd2a8"

[setting.minimum_liquidity_ratio]
defaultValue = "<%= parseEther('1.25') %>" # 125% min market collateralization

[setting.account_timeout_withdraw]
defaultValue = "86400" # 1 day

[setting.main_pool_id]
defaultValue = "1"

[setting.pool_owner]
defaultValue = "0x9f76043B23125024Ce5f0Fb4AE707482107dd2a8"

[invoke.setMainPoolConfig]
target = ["system.CoreProxy"]
fromCall.func = "getPoolOwner"
fromCall.args = ["<%= settings.main_pool_id %>"]
func = "setPoolConfiguration"
args = [
    "<%= settings.main_pool_id %>",
    [
        { marketId = "<%= imports.perpsFactory.extras.superMarketId %>", weightD18 = 1, maxDebtShareValueD18 = "<%= parseEther('1') %>" },
    ],
]

[setting.usdc_address]
defaultValue = "0x17C9D8Cef7Ef072844EEaEdE1F9f54C7E3fa8743"
