name = "polynomial-mainnet"
version = "1"
description = "Andromeda dev deployment"
preset = "main"
include = [
    "tomls/core.toml",
    "tomls/settings.toml",
    "tomls/permissions.toml",
    "tomls/permit-deniers.toml",
    "tomls/pools/main-pool.toml",
    "tomls/markets/spot-factory.toml",
    "tomls/markets/perps-factory.toml",
    "tomls/markets/common/bigcap-settings.toml",
    "tomls/polynomial-mainnet-andromeda/spot/usdc.toml",
    "tomls/permit-all-perps-perpsSystem.toml",
    "tomls/polynomial-mainnet-andromeda/perps/referrers.toml",
    "tomls/polynomial-mainnet-andromeda/perps/global.toml",
    "tomls/polynomial-mainnet-andromeda/spot/global.toml",
    "tomls/polynomial-mainnet-andromeda/perps/fee-tier.toml",
    "tomls/oracles/perps-keeper-cost.toml",
    "tomls/polynomial-mainnet-andromeda/spot/eth.toml",
    "tomls/polynomial-mainnet-andromeda/spot/op.toml",
    "tomls/polynomial-mainnet-andromeda/spot/wstEth.toml",
    "tomls/polynomial-mainnet-andromeda/spot/solvBtc.toml",
    "tomls/polynomial-mainnet-andromeda/spot/weEth.toml",
    "tomls/polynomial-mainnet-andromeda/collaterals/susdc.toml",
    "tomls/collaterals/susdc.toml",
    "tomls/polynomial-mainnet-andromeda/collaterals/sdai.toml",
    "tomls/oracles/pyth-sdai.toml",
    "tomls/oracles/pyth-usdc.toml",
    "tomls/oracles/sdai.toml",
    "tomls/collaterals/sdai.toml",
    "tomls/polynomial-mainnet-andromeda/collaterals/susde.toml",
    "tomls/oracles/pyth-susde.toml",
    "tomls/oracles/susde.toml",
    "tomls/collaterals/susde.toml",
    "tomls/polynomial-mainnet-andromeda/collaterals/usd0++.toml",
    "tomls/oracles/pyth-usd0++.toml",
    "tomls/oracles/usd0++.toml",
    "tomls/collaterals/usd0++.toml",
    "tomls/polynomial-mainnet-andromeda/perps/collaterals/usd.toml",
    "tomls/polynomial-mainnet-andromeda/perps/collaterals/eth.toml",
    "tomls/polynomial-mainnet-andromeda/perps/collaterals/op.toml",
    "tomls/polynomial-mainnet-andromeda/perps/collaterals/wstEth.toml",
    "tomls/polynomial-mainnet-andromeda/perps/collaterals/solvBtc.toml",
    "tomls/polynomial-mainnet-andromeda/perps/collaterals/weEth.toml",
    "tomls/polynomial-mainnet-andromeda/rewards/fxeth_perps_liquidations_rewards.toml",
    "tomls/polynomial-mainnet-andromeda/rewards/fxop_perps_liquidations_rewards.toml",
    "tomls/polynomial-mainnet-andromeda/rewards/fxwsteth_perps_liquidations_rewards.toml",
    "tomls/polynomial-mainnet-andromeda/rewards/fxsolvbtc_perps_liquidations_rewards.toml",
    "tomls/polynomial-mainnet-andromeda/rewards/fxweeth_perps_liquidations_rewards.toml",
    "tomls/polynomial-mainnet-andromeda/perps/btc-invokes.toml",
    "tomls/oracles/pyth-wsteth.toml",
    "tomls/oracles/pyth-solvbtc.toml",
    "tomls/oracles/pyth-weeth.toml",
    "tomls/oracles/pyth-btc.toml",
    "tomls/polynomial-mainnet-andromeda/perps/btc.toml",
    "tomls/polynomial-mainnet-andromeda/perps/eth-invokes.toml",
    "tomls/oracles/pyth-eth.toml",
    "tomls/polynomial-mainnet-andromeda/perps/eth.toml",
    "tomls/polynomial-mainnet-andromeda/perps/sol-invokes.toml",
    "tomls/oracles/pyth-sol.toml",
    "tomls/polynomial-mainnet-andromeda/perps/sol.toml",
    "tomls/polynomial-mainnet-andromeda/perps/pepe-invokes.toml",
    "tomls/oracles/pyth-pepe.toml",
    "tomls/polynomial-mainnet-andromeda/perps/pepe.toml",
    "tomls/polynomial-mainnet-andromeda/perps/wif-invokes.toml",
    "tomls/oracles/pyth-wif.toml",
    "tomls/polynomial-mainnet-andromeda/perps/wif.toml",
    "tomls/polynomial-mainnet-andromeda/perps/sui-invokes.toml",
    "tomls/oracles/pyth-sui.toml",
    "tomls/polynomial-mainnet-andromeda/perps/sui.toml",
    "tomls/polynomial-mainnet-andromeda/perps/aave-invokes.toml",
    "tomls/oracles/pyth-aave.toml",
    "tomls/polynomial-mainnet-andromeda/perps/aave.toml",
    "tomls/polynomial-mainnet-andromeda/perps/op-invokes.toml",
    "tomls/oracles/pyth-op.toml",
    "tomls/polynomial-mainnet-andromeda/perps/op.toml",
    "tomls/polynomial-mainnet-andromeda/perps/bonk-invokes.toml",
    "tomls/oracles/pyth-bonk.toml",
    "tomls/polynomial-mainnet-andromeda/perps/bonk.toml",
    "tomls/polynomial-mainnet-andromeda/perps/pnut-invokes.toml",
    "tomls/oracles/pyth-pnut.toml",
    "tomls/polynomial-mainnet-andromeda/perps/pnut.toml",
    "tomls/polynomial-mainnet-andromeda/perps/mog-invokes.toml",
    "tomls/oracles/pyth-mog.toml",
    "tomls/polynomial-mainnet-andromeda/perps/mog.toml",
    "tomls/polynomial-mainnet-andromeda/perps/ena-invokes.toml",
    "tomls/oracles/pyth-ena.toml",
    "tomls/polynomial-mainnet-andromeda/perps/ena.toml",
    "tomls/polynomial-mainnet-andromeda/perps/doge-invokes.toml",
    "tomls/oracles/pyth-doge.toml",
    "tomls/polynomial-mainnet-andromeda/perps/doge.toml",
    "tomls/polynomial-mainnet-andromeda/perps/eigen-invokes.toml",
    "tomls/oracles/pyth-eigen.toml",
    "tomls/polynomial-mainnet-andromeda/perps/eigen.toml",
    "tomls/polynomial-mainnet-andromeda/perps/xrp-invokes.toml",
    "tomls/oracles/pyth-xrp.toml",
    "tomls/polynomial-mainnet-andromeda/perps/xrp.toml",
    "tomls/polynomial-mainnet-andromeda/perps/tia-invokes.toml",
    "tomls/oracles/pyth-tia.toml",
    "tomls/polynomial-mainnet-andromeda/perps/tia.toml",
    "tomls/polynomial-mainnet-andromeda/perps/avax-invokes.toml",
    "tomls/oracles/pyth-avax.toml",
    "tomls/polynomial-mainnet-andromeda/perps/avax.toml",
    "tomls/polynomial-mainnet-andromeda/perps/ltc-invokes.toml",
    "tomls/oracles/pyth-ltc.toml",
    "tomls/polynomial-mainnet-andromeda/perps/ltc.toml",
    "tomls/polynomial-mainnet-andromeda/perps/link-invokes.toml",
    "tomls/oracles/pyth-link.toml",
    "tomls/polynomial-mainnet-andromeda/perps/link.toml",
    "tomls/polynomial-mainnet-andromeda/perps/pengu-invokes.toml",
    "tomls/oracles/pyth-pengu.toml",
    "tomls/polynomial-mainnet-andromeda/perps/pengu.toml",
    "tomls/polynomial-mainnet-andromeda/perps/virtual-invokes.toml",
    "tomls/oracles/pyth-virtual.toml",
    "tomls/polynomial-mainnet-andromeda/perps/virtual.toml",
    "tomls/polynomial-mainnet-andromeda/perps/hype-invokes.toml",
    "tomls/oracles/pyth-hype.toml",
    "tomls/polynomial-mainnet-andromeda/perps/hype.toml",
    "tomls/polynomial-mainnet-andromeda/perps/fartcoin-invokes.toml",
    "tomls/oracles/pyth-fartcoin.toml",
    "tomls/polynomial-mainnet-andromeda/perps/fartcoin.toml",
    "tomls/polynomial-mainnet-andromeda/perps/move-invokes.toml",
    "tomls/oracles/pyth-move.toml",
    "tomls/polynomial-mainnet-andromeda/perps/move.toml",
    "tomls/polynomial-mainnet-andromeda/perps/ai16z-invokes.toml",
    "tomls/oracles/pyth-ai16z.toml",
    "tomls/polynomial-mainnet-andromeda/perps/ai16z.toml",
    "tomls/polynomial-mainnet-andromeda/perps/snx-invokes.toml",
    "tomls/oracles/pyth-snx.toml",
    "tomls/polynomial-mainnet-andromeda/perps/snx.toml",
    "tomls/polynomial-mainnet-andromeda/perps/pyth-invokes.toml",
    "tomls/oracles/pyth-pyth.toml",
    "tomls/polynomial-mainnet-andromeda/perps/pyth.toml",
    "tomls/polynomial-mainnet-andromeda/perps/spx-invokes.toml",
    "tomls/oracles/pyth-spx.toml",
    "tomls/polynomial-mainnet-andromeda/perps/spx.toml",
    "tomls/polynomial-mainnet-andromeda/perps/trump-invokes.toml",
    "tomls/oracles/pyth-trump.toml",
    "tomls/polynomial-mainnet-andromeda/perps/trump.toml",
    "tomls/polynomial-mainnet-andromeda/perps/s-invokes.toml",
    "tomls/oracles/pyth-s.toml",
    "tomls/polynomial-mainnet-andromeda/perps/s.toml",
    "tomls/polynomial-mainnet-andromeda/perps/ondo-invokes.toml",
    "tomls/oracles/pyth-ondo.toml",
    "tomls/polynomial-mainnet-andromeda/perps/ondo.toml",
    "tomls/polynomial-mainnet-andromeda/perps/jup-invokes.toml",
    "tomls/oracles/pyth-jup.toml",
    "tomls/polynomial-mainnet-andromeda/perps/jup.toml",
    "tomls/polynomial-mainnet-andromeda/perps/bera-invokes.toml",
    "tomls/oracles/pyth-bera.toml",
    "tomls/polynomial-mainnet-andromeda/perps/bera.toml",
    "tomls/polynomial-mainnet-andromeda/perps/ada-invokes.toml",
    "tomls/oracles/pyth-ada.toml",
    "tomls/polynomial-mainnet-andromeda/perps/ada.toml",
    "tomls/polynomial-mainnet-andromeda/perps/bnb-invokes.toml",
    "tomls/oracles/pyth-bnb.toml",
    "tomls/polynomial-mainnet-andromeda/perps/bnb.toml",
    "tomls/polynomial-mainnet-andromeda/perps/arb-invokes.toml",
    "tomls/oracles/pyth-arb.toml",
    "tomls/polynomial-mainnet-andromeda/perps/arb.toml",
    "tomls/polynomial-mainnet-andromeda/perps/kaito-invokes.toml",
    "tomls/oracles/pyth-kaito.toml",
    "tomls/polynomial-mainnet-andromeda/perps/kaito.toml",
    "tomls/polynomial-mainnet-andromeda/perps/ip-invokes.toml",
    "tomls/oracles/pyth-ip.toml",
    "tomls/polynomial-mainnet-andromeda/perps/ip.toml",
    "tomls/polynomial-mainnet-andromeda/perps/hbar-invokes.toml",
    "tomls/oracles/pyth-hbar.toml",
    "tomls/polynomial-mainnet-andromeda/perps/hbar.toml",
    "tomls/polynomial-mainnet-andromeda/perps/bch-invokes.toml",
    "tomls/oracles/pyth-bch.toml",
    "tomls/polynomial-mainnet-andromeda/perps/bch.toml",
    "tomls/polynomial-mainnet-andromeda/perps/zora-invokes.toml",
    "tomls/oracles/pyth-zora.toml",
    "tomls/polynomial-mainnet-andromeda/perps/zora.toml",
    "tomls/polynomial-mainnet-andromeda/perps/cookie-invokes.toml",
    "tomls/oracles/pyth-cookie.toml",
    "tomls/polynomial-mainnet-andromeda/perps/cookie.toml",
]

[setting.commitmentPriceDelay]
defaultValue = "2"

[setting.bigCapSettlementDelay]
defaultValue = "2"

[setting.snx_package]
defaultValue = "polynomial-core:3.9.7"

[setting.perps_keeper_cost_package]
defaultValue = "fx-op-gas-price-oracle:3.8.2"

[setting.spot_market_package]
defaultValue = "fx-spot-market:3.9.7"

[setting.perps_market_package]
defaultValue = "fx-perps-market:3.9.9"

[setting.salt]
defaultValue = "andromeda-dev"

[setting.target_preset]
defaultValue = "main"

[setting.pyth_price_verification_address]
defaultValue = "0x2880aB155794e7179c9eE2e38200202908C17B43"

[setting.owner]
defaultValue = "0x9f76043B23125024Ce5f0Fb4AE707482107dd2a8"

[setting.deployer]
defaultValue = "0x9f76043B23125024Ce5f0Fb4AE707482107dd2a8"

[setting.minimum_liquidity_ratio]
defaultValue = "<%= parseEther('1.25') %>"

[setting.account_timeout_withdraw]
defaultValue = "86400"

[setting.main_pool_id]
defaultValue = "1"

[setting.pool_owner]
defaultValue = "0x9f76043B23125024Ce5f0Fb4AE707482107dd2a8"

[setting.usdc_address]
defaultValue = "0x17C9D8Cef7Ef072844EEaEdE1F9f54C7E3fa8743"

[provision.pyth_erc7412_wrapper]
source = "fx-pyth-erc7412-wrapper:3.4.0"
targetPreset = "<%= settings.target_preset %>"

[provision.pyth_erc7412_wrapper.options]
salt = "<%= settings.salt %>"
pythAddress = "<%= settings.pyth_price_verification_address %>"

[invoke.setMainPoolConfig]
target = [
    "system.CoreProxy",
]
func = "setPoolConfiguration"
args = [
    "<%= settings.main_pool_id %>",
    [
        { marketId = "<%= imports.perpsFactory.extras.superMarketId %>", weightD18 = 1, maxDebtShareValueD18 = "<%= parseEther('1') %>" },
    ],
]

[invoke.setMainPoolConfig.fromCall]
func = "getPoolOwner"
args = [
    "<%= settings.main_pool_id %>",
]
