[setting.strategy_market_package]

[provision.strategyFactory]
source = "<%= settings.strategy_market_package %>"
targetPreset = "<%= settings.target_preset %>"
options.owner = "<%= settings.owner %>"
options.salt = "<%= settings.salt %>"
depends = ["provision.system"]