[var.perps_collateral_CBBTC_settings]
cbbtc_upper_limit_discount = "<%= parseEther('0.12') %>"
cbbtc_lower_limit_discount = "<%= parseEther('0.05') %>"
cbbtc_discount_scalar = "<%= parseEther('1') %>"

[invoke.setPerpsMaxCollateralForFxCbBtc]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setCollateralConfiguration"
args = [
    "<%= extras.fx_cbbtc_market_id %>",
    "<%= settings.fxCbBtcMaxMarketCollateral %>",
    "<%= settings.cbbtc_upper_limit_discount %>",
    "<%= settings.cbbtc_lower_limit_discount %>",
    "<%= settings.cbbtc_discount_scalar %>",
]

[invoke.setSynthMaxMarketCollateralFxCbBtc]
target = ["system.CoreProxy"]
fromCall.func = "owner"
fromCall.args = []
func = "configureMaximumMarketCollateral"
args = [
    "<%= imports.perpsFactory.extras.superMarketId %>",
    "<%= extras.fx_cbbtc_token_address %>",
    "<%= settings.fxCbBtcMaxMarketCollateral %>",
]
