[var.perps_collateral_USDS_settings]
usds_upper_limit_discount = "<%= parseEther('0.05') %>"
usds_lower_limit_discount = "<%= parseEther('0.01') %>"
usds_discount_scalar = "<%= parseEther('1') %>"

[invoke.setPerpsMaxCollateralForFxUsds]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setCollateralConfiguration"
args = [
    "<%= extras.fx_usds_market_id %>",
    "<%= settings.fxUsdsMaxMarketCollateral %>",
    "<%= settings.usds_upper_limit_discount %>",
    "<%= settings.usds_lower_limit_discount %>",
    "<%= settings.usds_discount_scalar %>",
]

[invoke.setSynthMaxMarketCollateralFxUsds]
target = ["system.CoreProxy"]
fromCall.func = "owner"
fromCall.args = []
func = "configureMaximumMarketCollateral"
args = [
    "<%= imports.perpsFactory.extras.superMarketId %>",
    "<%= extras.fx_usds_token_address %>",
    "<%= settings.fxUsdsMaxMarketCollateral %>",
]
