[var.perps_collateral_USDT_settings]
usdt_upper_limit_discount = "<%= parseEther('0.05') %>"
usdt_lower_limit_discount = "<%= parseEther('0.01') %>"
usdt_discount_scalar = "<%= parseEther('1') %>"

[invoke.setPerpsMaxCollateralForFxUsdt]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setCollateralConfiguration"
args = [
    "<%= extras.fx_usdt_market_id %>",
    "<%= settings.fxUsdtMaxMarketCollateral %>",
    "<%= settings.usdt_upper_limit_discount %>",
    "<%= settings.usdt_lower_limit_discount %>",
    "<%= settings.usdt_discount_scalar %>",
]

[invoke.setSynthMaxMarketCollateralFxUsdt]
target = ["system.CoreProxy"]
fromCall.func = "owner"
fromCall.args = []
func = "configureMaximumMarketCollateral"
args = [
    "<%= imports.perpsFactory.extras.superMarketId %>",
    "<%= extras.fx_usdt_token_address %>",
    "<%= settings.fxUsdtMaxMarketCollateral %>",
]
