[setting.deployer]

[setting.main_pool_id]

[setting.pool_owner]

[invoke.createMainPool]
target = ["system.CoreProxy"]
from = "<%= settings.deployer %>"
func = "createPool"
args = ["<%= settings.main_pool_id %>", "<%= settings.pool_owner %>"]
depends = ["invoke.permitCreatePool"]

[invoke.setMainPoolName]
target = ["system.CoreProxy"]
fromCall.func = "getPoolOwner"
fromCall.args = ["<%= settings.main_pool_id %>"]
func = "setPoolName"
args = ["<%= settings.main_pool_id %>", "Polynomial Main Pool"]
depends = ["invoke.createMainPool"]

[invoke.setPreferredPool]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setPreferredPool"
args = ["<%= settings.main_pool_id %>"]
depends = ["invoke.createMainPool"]
