[setting.deployer]

[setting.skibidi_pool_id]

[setting.pool_owner]

[invoke.createSkibidiPool]
target = ["system.CoreProxy"]
from = "<%= settings.deployer %>"
func = "createPool"
args = ["<%= settings.skibidi_pool_id %>", "<%= settings.pool_owner %>"]
depends = ["invoke.permitCreatePool"]

[invoke.setSkibidiPoolName]
target = ["system.CoreProxy"]
fromCall.func = "getPoolOwner"
fromCall.args = ["<%= settings.skibidi_pool_id %>"]
func = "setPoolName"
args = ["<%= settings.skibidi_pool_id %>", "Polynomial Skibidi Pool"]
depends = ["invoke.createSkibidiPool"]
