[invoke.registerperpsHumaPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsHumaFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsHumaPythOracleNode.extra.perpsHuma_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsHumaLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsHumaFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsHumaLookupOracleNode.extra.perpsHuma_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsHumaOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsHuma_pyth_oracle_id %>",
        "<%= extras.perpsHuma_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsHumaOracleNode.extra.perpsHuma_oracle_id]
event = "NodeRegistered"
arg = 0
