[invoke.registerperpsTonPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsTonFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsTonPythOracleNode.extra.perpsTon_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsTonLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsTonFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsTonLookupOracleNode.extra.perpsTon_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsTonOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsTon_pyth_oracle_id %>",
        "<%= extras.perpsTon_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsTonOracleNode.extra.perpsTon_oracle_id]
event = "NodeRegistered"
arg = 0
