[invoke.registerperpsCakePythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsCakeFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsCakePythOracleNode.extra.perpsCake_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsCakeLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsCakeFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsCakeLookupOracleNode.extra.perpsCake_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsCakeOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsCake_pyth_oracle_id %>",
        "<%= extras.perpsCake_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsCakeOracleNode.extra.perpsCake_oracle_id]
event = "NodeRegistered"
arg = 0
