[invoke.registerperpsFlokiPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsFlokiFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsFlokiPythOracleNode.extra.perpsFloki_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsFlokiLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsFlokiFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsFlokiLookupOracleNode.extra.perpsFloki_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsFlokiOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsFloki_pyth_oracle_id %>",
        "<%= extras.perpsFloki_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsFlokiOracleNode.extra.perpsFloki_oracle_id]
event = "NodeRegistered"
arg = 0
