[invoke.registerperpsPendlePythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsPendleFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsPendlePythOracleNode.extra.perpsPendle_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsPendleLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsPendleFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsPendleLookupOracleNode.extra.perpsPendle_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsPendleOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsPendle_pyth_oracle_id %>",
        "<%= extras.perpsPendle_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsPendleOracleNode.extra.perpsPendle_oracle_id]
event = "NodeRegistered"
arg = 0
