[invoke.registerperpsBeraPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsBeraFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsBeraPythOracleNode.extra.perpsBera_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsBeraLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsBeraFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsBeraLookupOracleNode.extra.perpsBera_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsBeraOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsBera_pyth_oracle_id %>",
        "<%= extras.perpsBera_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsBeraOracleNode.extra.perpsBera_oracle_id]
event = "NodeRegistered"
arg = 0
