[setting.pythWstethFeedId]
defaultValue = "0x6df640f3b8963d8f8358f791f352b8364513f6ab1cca5ed3f1f7b5448980e784"

# This registers a staleness node that looks to Pyth for a fresh enough price, or otherwise reverts with an ERC-7412 compatible error
# Latest Pyth Price
[invoke.registerPythWstethOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    5, # 5 = pyth aggregator type
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.pythWstethFeedId, false]) %>",
    [
    ],
]
depends = ["provision.system"]
extra.wsteth_pyth_oracle_id.event = "NodeRegistered"
extra.wsteth_pyth_oracle_id.arg = 0

# Pyth Off-chain Lookup
[invoke.registerLookupWstethOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    9, # 9 = PythOffchainLookupNode
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.pythWstethFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [
    ],
]
depends = ["provision.system"]
extra.wsteth_lookup_oracle_id.event = "NodeRegistered"
extra.wsteth_lookup_oracle_id.arg = 0

# Staleness Node
[invoke.registerWstethOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    7, # 7 = staleness circuit breaker
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.wsteth_pyth_oracle_id %>",
        "<%= extras.wsteth_lookup_oracle_id %>",
    ],
]
depends = ["provision.system"]
extra.wsteth_oracle_id.event = "NodeRegistered"
extra.wsteth_oracle_id.arg = 0