[invoke.registerperpsPythPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsPythFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsPythPythOracleNode.extra.perpsPyth_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsPythLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsPythFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsPythLookupOracleNode.extra.perpsPyth_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsPyth_pyth_oracle_id %>",
        "<%= extras.perpsPyth_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsPythOracleNode.extra.perpsPyth_oracle_id]
event = "NodeRegistered"
arg = 0
