[invoke.registerperpsSpxPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsSpxFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsSpxPythOracleNode.extra.perpsSpx_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsSpxLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsSpxFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsSpxLookupOracleNode.extra.perpsSpx_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsSpxOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsSpx_pyth_oracle_id %>",
        "<%= extras.perpsSpx_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsSpxOracleNode.extra.perpsSpx_oracle_id]
event = "NodeRegistered"
arg = 0
