[setting.pythRsEthFeedId]
defaultValue = "0x0caec284d34d836ca325cf7b3256c078c597bc052fbd3c0283d52b581d68d71f"

# This registers a staleness node that looks to Pyth for a fresh enough price, or otherwise reverts with an ERC-7412 compatible error
# Latest Pyth Price
[invoke.registerPythRsEthOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    5, # 5 = pyth aggregator type
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.pythRsEthFeedId, false]) %>",
    [
    ],
]
depends = ["provision.system"]
extra.rseth_pyth_oracle_id.event = "NodeRegistered"
extra.rseth_pyth_oracle_id.arg = 0

# Pyth Off-chain Lookup
[invoke.registerLookupRsEthOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    9, # 9 = PythOffchainLookupNode
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.pythRsEthFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [
    ],
]
depends = ["provision.system"]
extra.rseth_lookup_oracle_id.event = "NodeRegistered"
extra.rseth_lookup_oracle_id.arg = 0

# Staleness Node
[invoke.registerRsEthOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    7, # 7 = staleness circuit breaker
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.rseth_pyth_oracle_id %>",
        "<%= extras.rseth_lookup_oracle_id %>",
    ],
]
depends = ["provision.system"]
extra.rseth_oracle_id.event = "NodeRegistered"
extra.rseth_oracle_id.arg = 0
