[invoke.registerperpsEthfiPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsEthfiFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsEthfiPythOracleNode.extra.perpsEthfi_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsEthfiLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsEthfiFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsEthfiLookupOracleNode.extra.perpsEthfi_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsEthfiOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsEthfi_pyth_oracle_id %>",
        "<%= extras.perpsEthfi_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsEthfiOracleNode.extra.perpsEthfi_oracle_id]
event = "NodeRegistered"
arg = 0
