# This registers a staleness node that looks to Pyth for a fresh enough price, or otherwise reverts with an ERC-7412 compatible error
# Latest Pyth Price
[setting.pythSUSDEFeedId]
# https://pyth.network/developers/price-feed-ids
defaultValue = "0xca3ba9a619a4b3755c10ac7d5e760275aa95e9823d38a84fedd416856cdba37c"


[invoke.registerPythSUSDEOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    5, # 5 = pyth aggregator type
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.pythSUSDEFeedId, false]) %>",
    [
    ],
]
extra.SUSDE_pyth_oracle_id.event = "NodeRegistered"
extra.SUSDE_pyth_oracle_id.arg = 0
depends = ["provision.system", "setting.pyth_price_verification_address", "setting.pythSUSDEFeedId"]

# Pyth Off-chain Lookup
[invoke.registerLookupSUSDEOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    9, # 9 = PythOffchainLookupNode
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.pythSUSDEFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [
    ],
]
extra.SUSDE_lookup_oracle_id.event = "NodeRegistered"
extra.SUSDE_lookup_oracle_id.arg = 0
depends = [
    "provision.system",
    "provision.pyth_erc7412_wrapper",
    "setting.pythSUSDEFeedId",
    "setting.bigCapDefaultStalenessTolerance"
]

# Staleness Node
[invoke.registerSUSDEOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    7, # 7 = staleness circuit breaker
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.SUSDE_pyth_oracle_id %>",
        "<%= extras.SUSDE_lookup_oracle_id %>",
    ],
]
extra.SUSDE_staleness_oracle_id.event = "NodeRegistered"
extra.SUSDE_staleness_oracle_id.arg = 0
