[invoke.registerperpsFilPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsFilFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsFilPythOracleNode.extra.perpsFil_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsFilLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsFilFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsFilLookupOracleNode.extra.perpsFil_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsFilOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsFil_pyth_oracle_id %>",
        "<%= extras.perpsFil_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsFilOracleNode.extra.perpsFil_oracle_id]
event = "NodeRegistered"
arg = 0
