[invoke.registerperpsStxPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsStxFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsStxPythOracleNode.extra.perpsStx_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsStxLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsStxFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsStxLookupOracleNode.extra.perpsStx_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsStxOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsStx_pyth_oracle_id %>",
        "<%= extras.perpsStx_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsStxOracleNode.extra.perpsStx_oracle_id]
event = "NodeRegistered"
arg = 0
