[invoke.registerSDAIOracle]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    # 1 = reducer node
    1,
    # 1 parameters: 1 operation = 8 for division decimal
    "<%= defaultAbiCoder.encode(['uint256'], [8]) %>",
    # 2 parent: 1 is sdai pyth node , 2 is usdc pyth node
    ["<%= extras.sdai_staleness_oracle_id %>", "<%= extras.USDC_staleness_oracle_id %>"],
]
extra.sdai_oracle_id.event = "NodeRegistered"
extra.sdai_oracle_id.arg = 0
