[invoke.registerperpsGrtPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsGrtFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsGrtPythOracleNode.extra.perpsGrt_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsGrtLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsGrtFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsGrtLookupOracleNode.extra.perpsGrt_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsGrtOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsGrt_pyth_oracle_id %>",
        "<%= extras.perpsGrt_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsGrtOracleNode.extra.perpsGrt_oracle_id]
event = "NodeRegistered"
arg = 0
