[invoke.registerperpsHbarPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsHbarFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsHbarPythOracleNode.extra.perpsHbar_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsHbarLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsHbarFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsHbarLookupOracleNode.extra.perpsHbar_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsHbarOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsHbar_pyth_oracle_id %>",
        "<%= extras.perpsHbar_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsHbarOracleNode.extra.perpsHbar_oracle_id]
event = "NodeRegistered"
arg = 0
