[setting.pythCbBtcFeedId]
defaultValue = "0x2817d7bfe5c64b8ea956e9a26f573ef64e72e4d7891f2d6af9bcc93f7aff9a97"

# This registers a staleness node that looks to Pyth for a fresh enough price, or otherwise reverts with an ERC-7412 compatible error
# Latest Pyth Price
[invoke.registerPythCbBtcOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    5, # 5 = pyth aggregator type
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.pythCbBtcFeedId, false]) %>",
    [
    ],
]
depends = ["provision.system"]
extra.cbbtc_pyth_oracle_id.event = "NodeRegistered"
extra.cbbtc_pyth_oracle_id.arg = 0

# Pyth Off-chain Lookup
[invoke.registerLookupCbBtcOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    9, # 9 = PythOffchainLookupNode
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.pythCbBtcFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [
    ],
]
depends = ["provision.system"]
extra.cbbtc_lookup_oracle_id.event = "NodeRegistered"
extra.cbbtc_lookup_oracle_id.arg = 0

# Staleness Node
[invoke.registerCbBtcOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    7, # 7 = staleness circuit breaker
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.cbbtc_pyth_oracle_id %>",
        "<%= extras.cbbtc_lookup_oracle_id %>",
    ],
]
depends = ["provision.system"]
extra.cbbtc_oracle_id.event = "NodeRegistered"
extra.cbbtc_oracle_id.arg = 0
