[invoke.registerperpsPumpPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsPumpFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsPumpPythOracleNode.extra.perpsPump_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsPumpLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsPumpFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsPumpLookupOracleNode.extra.perpsPump_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsPumpOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsPump_pyth_oracle_id %>",
        "<%= extras.perpsPump_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsPumpOracleNode.extra.perpsPump_oracle_id]
event = "NodeRegistered"
arg = 0
