[setting.pythUsdtFeedId]
defaultValue = "0x2b89b9dc8fdf9f34709a5b106b472f0f39bb6ca9ce04b0fd7f2e971688e2e53b"

# This registers a staleness node that looks to Pyth for a fresh enough price, or otherwise reverts with an ERC-7412 compatible error
# Latest Pyth Price
[invoke.registerPythUsdtOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    5, # 5 = pyth aggregator type
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.pythUsdtFeedId, false]) %>",
    [
    ],
]
depends = ["provision.system"]
extra.usdt_pyth_oracle_id.event = "NodeRegistered"
extra.usdt_pyth_oracle_id.arg = 0

# Pyth Off-chain Lookup
[invoke.registerLookupUsdtOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    9, # 9 = PythOffchainLookupNode
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.pythUsdtFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [
    ],
]
depends = ["provision.system"]
extra.usdt_lookup_oracle_id.event = "NodeRegistered"
extra.usdt_lookup_oracle_id.arg = 0

# Staleness Node
[invoke.registerUsdtOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    7, # 7 = staleness circuit breaker
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.usdt_pyth_oracle_id %>",
        "<%= extras.usdt_lookup_oracle_id %>",
    ],
]
depends = ["provision.system"]
extra.usdt_oracle_id.event = "NodeRegistered"
extra.usdt_oracle_id.arg = 0
