# This registers a staleness node that looks to Pyth for a fresh enough price, or otherwise reverts with an ERC-7412 compatible error
# Latest Pyth Price
[invoke.registerPythQqqOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    5, # 5 = pyth aggregator type
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.pythQqqFeedId, false]) %>",
    [
    ],
]
depends = ["provision.system"]
extra.qqq_pyth_oracle_id.event = "NodeRegistered"
extra.qqq_pyth_oracle_id.arg = 0

# Pyth Off-chain Lookup
[invoke.registerLookupQqqOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    9, # 9 = PythOffchainLookupNode
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.pythQqqFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [
    ],
]
depends = ["provision.system"]
extra.qqq_lookup_oracle_id.event = "NodeRegistered"
extra.qqq_lookup_oracle_id.arg = 0

# Staleness Node
[invoke.registerQqqOracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    7, # 7 = staleness circuit breaker
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.qqq_pyth_oracle_id %>",
        "<%= extras.qqq_lookup_oracle_id %>",
    ],
]
depends = ["provision.system"]
extra.qqq_oracle_id.event = "NodeRegistered"
extra.qqq_oracle_id.arg = 0
