# This registers a staleness node that looks to Pyth for a fresh enough price, or otherwise reverts with an ERC-7412 compatible error
# Latest Pyth Price
[setting.pythUsd0FeedId]
# https://pyth.network/developers/price-feed-ids
defaultValue = "0xf9c96a45784d0ce4390825a43a313149da787e6a6c66076f3a3f83e92501baeb"


[invoke.registerPythUsd0OracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    5, # 5 = pyth aggregator type
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.pythUsd0FeedId, false]) %>",
    [
    ],
]
extra.usd0_pyth_oracle_id.event = "NodeRegistered"
extra.usd0_pyth_oracle_id.arg = 0
depends = [
    "provision.system",
    "setting.pyth_price_verification_address",
    "setting.pythUsd0FeedId",
]

# Pyth Off-chain Lookup
[invoke.registerLookupUsd0OracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    9, # 9 = PythOffchainLookupNode
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.pythUsd0FeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [
    ],
]
extra.usd0_lookup_oracle_id.event = "NodeRegistered"
extra.usd0_lookup_oracle_id.arg = 0
depends = [
    "provision.system",
    "provision.pyth_erc7412_wrapper",
    "setting.pythUsd0FeedId",
    "setting.bigCapDefaultStalenessTolerance",
]

# Staleness Node
[invoke.registerUsd0OracleNode]
target = ["system.oracle_manager.Proxy"]
func = "registerNode"
args = [
    7, # 7 = staleness circuit breaker
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.usd0_pyth_oracle_id %>",
        "<%= extras.usd0_lookup_oracle_id %>",
    ],
]
extra.usd0_staleness_oracle_id.event = "NodeRegistered"
extra.usd0_staleness_oracle_id.arg = 0
