[invoke.registerperpsPrclPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsPrclFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsPrclPythOracleNode.extra.perpsPrcl_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsPrclLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsPrclFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsPrclLookupOracleNode.extra.perpsPrcl_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsPrclOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsPrcl_pyth_oracle_id %>",
        "<%= extras.perpsPrcl_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsPrclOracleNode.extra.perpsPrcl_oracle_id]
event = "NodeRegistered"
arg = 0
