[invoke.registerperpsArkmPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsArkmFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsArkmPythOracleNode.extra.perpsArkm_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsArkmLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsArkmFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsArkmLookupOracleNode.extra.perpsArkm_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsArkmOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsArkm_pyth_oracle_id %>",
        "<%= extras.perpsArkm_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsArkmOracleNode.extra.perpsArkm_oracle_id]
event = "NodeRegistered"
arg = 0
