[invoke.registerperpsMerlPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsMerlFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsMerlPythOracleNode.extra.perpsMerl_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsMerlLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsMerlFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsMerlLookupOracleNode.extra.perpsMerl_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsMerlOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsMerl_pyth_oracle_id %>",
        "<%= extras.perpsMerl_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsMerlOracleNode.extra.perpsMerl_oracle_id]
event = "NodeRegistered"
arg = 0
