[invoke.registerperpsWldPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsWldFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsWldPythOracleNode.extra.perpsWld_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsWldLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsWldFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsWldLookupOracleNode.extra.perpsWld_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsWldOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsWld_pyth_oracle_id %>",
        "<%= extras.perpsWld_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsWldOracleNode.extra.perpsWld_oracle_id]
event = "NodeRegistered"
arg = 0
