[invoke.registerperpsAltPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsAltFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsAltPythOracleNode.extra.perpsAlt_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsAltLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsAltFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsAltLookupOracleNode.extra.perpsAlt_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsAltOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsAlt_pyth_oracle_id %>",
        "<%= extras.perpsAlt_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsAltOracleNode.extra.perpsAlt_oracle_id]
event = "NodeRegistered"
arg = 0
