[invoke.registerperpsResolvPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsResolvFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsResolvPythOracleNode.extra.perpsResolv_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsResolvLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsResolvFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsResolvLookupOracleNode.extra.perpsResolv_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsResolvOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsResolv_pyth_oracle_id %>",
        "<%= extras.perpsResolv_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsResolvOracleNode.extra.perpsResolv_oracle_id]
event = "NodeRegistered"
arg = 0
