[invoke.registerperpsTrumpPythOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    5,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'bool'], [settings.pyth_price_verification_address, settings.perpsTrumpFeedId, false]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsTrumpPythOracleNode.extra.perpsTrump_pyth_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsTrumpLookupOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    9,
    "<%= defaultAbiCoder.encode(['address', 'bytes32', 'uint256'], [imports.pyth_erc7412_wrapper.contracts.PythERC7412Wrapper.address, settings.perpsTrumpFeedId, settings.bigCapDefaultStalenessTolerance]) %>",
    [],
]
depends = [
    "provision.system",
]

[invoke.registerperpsTrumpLookupOracleNode.extra.perpsTrump_lookup_oracle_id]
event = "NodeRegistered"
arg = 0

[invoke.registerperpsTrumpOracleNode]
target = [
    "system.oracle_manager.Proxy",
]
func = "registerNode"
args = [
    7,
    "<%= defaultAbiCoder.encode(['uint256'], [settings.bigCapDefaultStalenessTolerance]) %>",
    [
        "<%= extras.perpsTrump_pyth_oracle_id %>",
        "<%= extras.perpsTrump_lookup_oracle_id %>",
    ],
]
depends = [
    "provision.system",
]

[invoke.registerperpsTrumpOracleNode.extra.perpsTrump_oracle_id]
event = "NodeRegistered"
arg = 0
