[var.perps_collateral_ETH_settings]
eth_upper_limit_discount = "<%= parseEther('0.1') %>"
eth_lower_limit_discount = "<%= parseEther('0.01') %>"
eth_discount_scalar = "<%= parseEther('1') %>"

[invoke.setPerpsMaxCollateralForFxUsd]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setCollateralConfiguration"
args = [
    "<%= extras.fx_eth_market_id %>",
    "<%= settings.fxEthMaxMarketCollateral %>",
    "<%= settings.eth_upper_limit_discount %>",
    "<%= settings.eth_lower_limit_discount %>",
    "<%= settings.eth_discount_scalar %>",
]

[invoke.setSynthMaxMarketCollateralFxEth]
target = ["system.CoreProxy"]
fromCall.func = "owner"
fromCall.args = []
func = "configureMaximumMarketCollateral"
args = [
    "<%= imports.perpsFactory.extras.superMarketId %>",
    "<%= extras.fx_eth_token_address %>",
    "<%= settings.fxEthMaxMarketCollateral %>",
]
