[var.perps_collateral_SOLVBTC_settings]
solvbtc_upper_limit_discount = "<%= parseEther('0.12') %>"
solvbtc_lower_limit_discount = "<%= parseEther('0.05') %>"
solvbtc_discount_scalar = "<%= parseEther('1') %>"

[invoke.setPerpsMaxCollateralForFxSolvbtc]
target = ["perpsFactory.PerpsMarketProxy"]
fromCall.func = "owner"
func = "setCollateralConfiguration"
args = [
    "<%= extras.fx_solvbtc_market_id %>",
    "<%= settings.fxSolvbtcMaxMarketCollateral %>",
    "<%= settings.solvbtc_upper_limit_discount %>",
    "<%= settings.solvbtc_lower_limit_discount %>",
    "<%= settings.solvbtc_discount_scalar %>",
]

[invoke.setSynthMaxMarketCollateralFxSolvbtc]
target = ["system.CoreProxy"]
fromCall.func = "owner"
fromCall.args = []
func = "configureMaximumMarketCollateral"
args = [
    "<%= imports.perpsFactory.extras.superMarketId %>",
    "<%= extras.fx_solvbtc_token_address %>",
    "<%= settings.fxSolvbtcMaxMarketCollateral %>",
]