[setting.spot_market_package]

[provision.spotFactory]
source = "<%= settings.spot_market_package %>"
targetPreset = "<%= settings.target_preset %>"
options.coreProxyOwner = "<%= settings.owner %>"
options.owner = "<%= settings.owner %>"
options.salt = "<%= settings.salt %>"
options.polynomialCore = "<%= settings.snx_package %>@<%= settings.target_preset %>"
options.polynomialCorePreset = "<%= settings.target_preset %>"
depends = ["provision.system"]
